use std::collections::HashSet;

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct CTarget;

impl CodeTarget for CTarget {
    fn name(&self) -> &str {
        "c"
    }

    fn file_extension(&self) -> &str {
        "c"
    }

    fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("/* Generated by Verun */\n");
        out.push_str("#include <assert.h>\n#include <stdbool.h>\n#include <stdint.h>\n#include <stdlib.h>\n\n");
        out.push_str("static inline int64_t verun_abs(int64_t x) { return x < 0 ? -x : x; }\n");
        out.push_str(
            "static inline int64_t verun_min(int64_t a, int64_t b) { return a < b ? a : b; }\n",
        );
        out.push_str(
            "static inline int64_t verun_max(int64_t a, int64_t b) { return a > b ? a : b; }\n\n",
        );

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => out.push_str(&self.gen_const(c)),
                Item::EnumDef(e) => out.push_str(&self.gen_enum(e)),
                _ => {}
            }
        }

        for item in &program.items {
            match &item.node {
                Item::TypeDef(t) => out.push_str(&self.gen_type_def(t)),
                Item::State(s) => out.push_str(&self.gen_state(s)),
                _ => {}
            }
        }

        out
    }
}

impl CTarget {
    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "static const {} {} = {};\n\n",
            self.type_to_c(&c.ty.node),
            c.name.node,
            self.expr_to_c(&c.value.node, &HashSet::new(), &HashSet::new(), false)
        )
    }

    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = format!("typedef enum {} {{\n", e.name.node);
        for (i, variant) in e.variants.iter().enumerate() {
            if i + 1 == e.variants.len() {
                out.push_str(&format!("    {}_{}\n", e.name.node, variant.node));
            } else {
                out.push_str(&format!("    {}_{},\n", e.name.node, variant.node));
            }
        }
        out.push_str(&format!("}} {};\n\n", e.name.node));
        out
    }

    fn gen_type_def(&self, t: &crate::ast::types::TypeDef) -> String {        if let Some(alias_ty) = &t.alias {
            return format!(
                "typedef {} {};\n\n",
                self.type_to_c(&alias_ty.node),
                t.name.node
            );
        }        let mut out = format!("typedef struct {} {{\n", t.name.node);
        for field in &t.fields {
            out.push_str(&format!(
                "    {} {};\n",
                self.type_to_c(&field.ty.node),
                field.name.node
            ));
        }
        out.push_str(&format!("}} {};\n\n", t.name.node));
        out
    }

    fn gen_state(&self, s: &StateDef) -> String {
        let mut out = String::new();

        for c in &s.constants {
            out.push_str(&self.gen_const(c));
        }

        out.push_str(&format!("typedef struct {} {{\n", s.name.node));
        for field in &s.fields {
            out.push_str(&format!(
                "    {} {};\n",
                self.type_to_c(&field.ty.node),
                field.name.node
            ));
        }
        out.push_str(&format!("}} {};\n\n", s.name.node));

        out.push_str(&format!(
            "void {}_init({}* self) {{\n",
            s.name.node.to_lowercase(),
            s.name.node
        ));
        if let Some(init) = &s.init {
            for assign in &init.assignments {
                out.push_str(&format!(
                    "    self->{} = {};\n",
                    assign.target.node,
                    self.expr_to_c(&assign.value.node, &HashSet::new(), &HashSet::new(), false)
                ));
            }
        }
        out.push_str("}\n\n");

        for t in &s.transitions {
            out.push_str(&self.gen_transition(s, t));
        }

        out
    }

    fn gen_transition(&self, s: &StateDef, t: &Transition) -> String {
        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{} {}", self.type_to_c(&p.ty.node), p.name.node))
            .collect();
        let mut full_params = vec![format!("{}* self", s.name.node)];
        full_params.extend(params);

        let params_set: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let fields_set: HashSet<String> = s.fields.iter().map(|f| f.name.node.clone()).collect();

        let mut out = format!(
            "void {}_{}({}) {{\n",
            s.name.node.to_lowercase(),
            t.name.node,
            full_params.join(", ")
        );

        for pre in &t.preconditions {
            out.push_str(&format!(
                "    assert({});\n",
                self.expr_to_c(&pre.node, &params_set, &fields_set, false)
            ));
        }

        for stmt in &t.body {
            out.push_str(&format!(
                "    {};\n",
                self.stmt_to_c(&stmt.node, &params_set, &fields_set)
            ));
        }

        for inv in &s.invariants {
            out.push_str(&format!(
                "    assert({});\n",
                self.expr_to_c(&inv.condition.node, &params_set, &fields_set, false)
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "    assert({});\n",
                self.expr_to_c(&post.node, &params_set, &fields_set, false)
            ));
        }

        out.push_str("}\n\n");
        out
    }

    fn type_to_c(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "int64_t".to_string(),
            Type::Real => "double".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "const char*".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, size } => format!("{}[{}]", self.type_to_c(element), size),
            Type::Map { .. } => "/* map unsupported in C target */ void*".to_string(),
        }
    }

    fn expr_to_c(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => v.to_string(),
            Expr::RealLit(v) => v.to_string(),
            Expr::BoolLit(v) => {
                if *v {
                    "1".to_string()
                } else {
                    "0".to_string()
                }
            }
            Expr::StringLit(v) => format!("\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("self->{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_c(&inner.node, params, fields, true),
            Expr::EnumVariant { enum_name, variant } => format!("{}_{}", enum_name, variant),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_c(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_c(&left.node, params, fields, in_old);
                let r = self.expr_to_c(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("((!{}) || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_c(&object.node, params, fields, in_old),
                    field.node
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[{}]",
                    self.expr_to_c(&object.node, params, fields, in_old),
                    self.expr_to_c(&index.node, params, fields, in_old)
                )
            }
            Expr::Forall { var, domain, body } => {
                self.quantifier_to_c(var, domain, body, params, fields, in_old, true)
            }
            Expr::Exists { var, domain, body } => {
                self.quantifier_to_c(var, domain, body, params, fields, in_old, false)
            }
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_c(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("verun_abs({})", arg_strs[0]),
                    "min" => format!("verun_min({}, {})", arg_strs[0], arg_strs[1]),
                    "max" => format!("verun_max({}, {})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "0 /* unsupported */".to_string(),
        }
    }

    fn stmt_to_c(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => format!(
                "self->{} = {}",
                assign.target.node,
                self.expr_to_c(&assign.value.node, params, fields, false)
            ),
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "self->{} {} {}",
                    target.node,
                    op_str,
                    self.expr_to_c(&value.node, params, fields, false)
                )
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => format!(
                "self->{}[{}] = {}",
                target.node,
                self.expr_to_c(&index.node, params, fields, false),
                self.expr_to_c(&value.node, params, fields, false)
            ),
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "self->{}[{}] {} {}",
                    target.node,
                    self.expr_to_c(&index.node, params, fields, false),
                    op_str,
                    self.expr_to_c(&value.node, params, fields, false)
                )
            }
            Statement::Assert { condition } => format!(
                "assert({})",
                self.expr_to_c(&condition.node, params, fields, false)
            ),
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let cond =
                    self.clean_condition(&self.expr_to_c(&condition.node, params, fields, false));
                let mut out = format!("if ({}) {{\n", cond);
                for s in then_body {
                    out.push_str(&format!(
                        "        {};\n",
                        self.stmt_to_c(&s.node, params, fields)
                    ));
                }
                out.push_str("    }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        out.push_str(&format!(
                            "        {};\n",
                            self.stmt_to_c(&s.node, params, fields)
                        ));
                    }
                    out.push_str("    }");
                }
                out
            }
            Statement::Let { name, ty, value } => {
                let declared = ty
                    .as_ref()
                    .map(|t| self.type_to_c(&t.node))
                    .unwrap_or_else(|| "int64_t".to_string());
                format!(
                    "{} {} = {}",
                    declared,
                    name.node,
                    self.expr_to_c(&value.node, params, fields, false)
                )
            }
            Statement::Match { expr, arms } => {
                let mut out = format!(
                    "switch ({}) {{\n",
                    self.expr_to_c(&expr.node, params, fields, false)
                );
                for arm in arms {
                    match &arm.pattern.node {
                        MatchPattern::Wildcard => out.push_str("    default:\n"),
                        _ => out.push_str(&format!(
                            "    case {}:\n",
                            self.match_pattern_c(&arm.pattern.node)
                        )),
                    }
                    for s in &arm.body {
                        out.push_str(&format!(
                            "        {};\n",
                            self.stmt_to_c(&s.node, params, fields)
                        ));
                    }
                    out.push_str("        break;\n");
                }
                out.push_str("    }");
                out
            }
        }
    }

    fn quantifier_to_c(
        &self,
        var: &crate::ast::span::Spanned<String>,
        domain: &crate::ast::span::Spanned<Expr>,
        body: &crate::ast::span::Spanned<Expr>,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
        is_forall: bool,
    ) -> String {
        if let Expr::Range { start, end } = &domain.node {
            let start_s = self.expr_to_c(&start.node, params, fields, in_old);
            let end_s = self.expr_to_c(&end.node, params, fields, in_old);
            let mut local_params = params.clone();
            local_params.insert(var.node.clone());
            let body_s = self.expr_to_c(&body.node, &local_params, fields, in_old);

            if is_forall {
                format!(
                    "({{ bool __verun_ok = true; for (int64_t {} = ({}); {} < ({}); ++{}) {{ if (!({})) {{ __verun_ok = false; break; }} }} __verun_ok; }})",
                    var.node, start_s, var.node, end_s, var.node, body_s
                )
            } else {
                format!(
                    "({{ bool __verun_ok = false; for (int64_t {} = ({}); {} < ({}); ++{}) {{ if (({})) {{ __verun_ok = true; break; }} }} __verun_ok; }})",
                    var.node, start_s, var.node, end_s, var.node, body_s
                )
            }
        } else if is_forall {
            "1".to_string()
        } else {
            "0".to_string()
        }
    }

    fn match_pattern_c(&self, p: &MatchPattern) -> String {
        match p {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{}_{}", enum_name, variant)
            }
            MatchPattern::IntLit(v) => v.to_string(),
            MatchPattern::BoolLit(v) => {
                if *v {
                    "1".to_string()
                } else {
                    "0".to_string()
                }
            }
            MatchPattern::StringLit(v) => format!("/* string '{}' unsupported in C switch */ 0", v),
            MatchPattern::Wildcard => "default".to_string(),
        }
    }

    fn clean_condition(&self, expr: &str) -> String {
        if expr.starts_with('(') && expr.ends_with(')') && expr.len() >= 2 {
            expr[1..expr.len() - 1].to_string()
        } else {
            expr.to_string()
        }
    }
}
