use std::collections::HashSet;

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct CairoTarget;

impl CodeTarget for CairoTarget {
    fn name(&self) -> &str {
        "cairo"
    }

    fn file_extension(&self) -> &str {
        "cairo"
    }

    fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("// Generated by Verun\n\n");

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => out.push_str(&self.gen_const(c)),
                Item::EnumDef(e) => out.push_str(&self.gen_enum(e)),
                _ => {}
            }
        }

        for item in &program.items {
            if let Item::State(state) = &item.node {
                out.push_str(&self.gen_state(state));
            }
        }

        out
    }
}

impl CairoTarget {
    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "const {}: {} = {};\n\n",
            c.name.node,
            self.type_to_cairo(&c.ty.node),
            self.expr_to_cairo(&c.value.node, &HashSet::new(), &HashSet::new(), false)
        )
    }

    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = format!("enum {} {{\n", e.name.node);
        for variant in &e.variants {
            out.push_str(&format!("    {},\n", variant.node));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_state(&self, state: &StateDef) -> String {
        let mut out = String::new();

        for c in &state.constants {
            out.push_str(&self.gen_const(c));
        }

        out.push_str(&format!("struct {} {{\n", state.name.node));
        for field in &state.fields {
            out.push_str(&format!(
                "    {}: {},\n",
                field.name.node,
                self.type_to_cairo(&field.ty.node)
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "fn {}_init() -> {} {{\n",
            state.name.node.to_lowercase(),
            state.name.node
        ));
        out.push_str(&format!("    let s = {} {{\n", state.name.node));
        for field in &state.fields {
            let value = if let Some(init) = &state.init {
                init.assignments
                    .iter()
                    .find(|a| a.target.node == field.name.node)
                    .map(|a| {
                        self.expr_to_cairo(&a.value.node, &HashSet::new(), &HashSet::new(), false)
                    })
                    .unwrap_or_else(|| "0".to_string())
            } else {
                "0".to_string()
            };
            out.push_str(&format!("        {}: {},\n", field.name.node, value));
        }
        out.push_str("    };\n");
        out.push_str("    s\n}\n\n");

        for t in &state.transitions {
            out.push_str(&self.gen_transition(state, t));
        }

        out
    }

    fn gen_transition(&self, state: &StateDef, t: &Transition) -> String {
        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name.node, self.type_to_cairo(&p.ty.node)))
            .collect();
        let mut full_params = vec![format!("ref s: {}", state.name.node)];
        full_params.extend(params);
        let param_set: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let field_set: HashSet<String> = state.fields.iter().map(|f| f.name.node.clone()).collect();

        let mut out = format!("fn {}({}) {{\n", t.name.node, full_params.join(", "));

        for pre in &t.preconditions {
            out.push_str(&format!(
                "    assert({});\n",
                self.expr_to_cairo(&pre.node, &param_set, &field_set, false)
            ));
        }

        for stmt in &t.body {
            out.push_str(&format!(
                "    {};\n",
                self.stmt_to_cairo(&stmt.node, &param_set, &field_set)
            ));
        }

        for inv in &state.invariants {
            out.push_str(&format!(
                "    assert({});\n",
                self.expr_to_cairo(&inv.condition.node, &param_set, &field_set, false)
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "    assert({});\n",
                self.expr_to_cairo(&post.node, &param_set, &field_set, false)
            ));
        }

        out.push_str("}\n\n");
        out
    }

    fn type_to_cairo(&self, ty: &Type) -> String {
        match ty {
            Type::Int | Type::Real => "felt252".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "felt252".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, .. } => format!("Array<{}>", self.type_to_cairo(element)),
            Type::Map { .. } => "Felt252Dict<felt252>".to_string(),
        }
    }

    fn expr_to_cairo(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => v.to_string(),
            Expr::RealLit(v) => format!("{}", *v as i64),
            Expr::BoolLit(v) => v.to_string(),
            Expr::StringLit(v) => format!("'{}'", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("s.{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_cairo(&inner.node, params, fields, true),
            Expr::EnumVariant { enum_name, variant } => format!("{}::{}", enum_name, variant),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_cairo(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_cairo(&left.node, params, fields, in_old);
                let r = self.expr_to_cairo(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("((!{}) || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Forall { .. } => "true".to_string(),
            Expr::Exists { .. } => "false".to_string(),
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_cairo(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("if ({0} > 0) {{ {0} }} else {{ 0 - {0} }}", arg_strs[0]),
                    "min" => format!(
                        "if ({0} < {1}) {{ {0} }} else {{ {1} }}",
                        arg_strs[0], arg_strs[1]
                    ),
                    "max" => format!(
                        "if ({0} > {1}) {{ {0} }} else {{ {1} }}",
                        arg_strs[0], arg_strs[1]
                    ),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "0".to_string(),
        }
    }

    fn stmt_to_cairo(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => format!(
                "s.{} = {}",
                assign.target.node,
                self.expr_to_cairo(&assign.value.node, params, fields, false)
            ),
            Statement::CompoundAssign { target, op, value } => {
                let rhs = self.expr_to_cairo(&value.node, params, fields, false);
                match op {
                    CompoundOp::Add => format!("s.{0} = s.{0} + {1}", target.node, rhs),
                    CompoundOp::Sub => format!("s.{0} = s.{0} - {1}", target.node, rhs),
                    CompoundOp::Mul => format!("s.{0} = s.{0} * {1}", target.node, rhs),
                    CompoundOp::Div => format!("s.{0} = s.{0} / {1}", target.node, rhs),
                }
            }
            Statement::Assert { condition } => format!(
                "assert({})",
                self.expr_to_cairo(&condition.node, params, fields, false)
            ),
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut out = format!(
                    "if ({}) {{\n",
                    self.expr_to_cairo(&condition.node, params, fields, false)
                );
                for s in then_body {
                    out.push_str(&format!(
                        "        {};\n",
                        self.stmt_to_cairo(&s.node, params, fields)
                    ));
                }
                out.push_str("    }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        out.push_str(&format!(
                            "        {};\n",
                            self.stmt_to_cairo(&s.node, params, fields)
                        ));
                    }
                    out.push_str("    }");
                }
                out
            }
            Statement::Let { name, value, .. } => format!(
                "let {} = {}",
                name.node,
                self.expr_to_cairo(&value.node, params, fields, false)
            ),
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_cairo(&expr.node, params, fields, false);
                let mut out = String::new();
                for (idx, arm) in arms.iter().enumerate() {
                    match &arm.pattern.node {
                        MatchPattern::Wildcard => out.push_str(" else {\n"),
                        _ => {
                            let kw = if idx == 0 { "if" } else { "else if" };
                            out.push_str(&format!(
                                "{} ({} == {}) {{\n",
                                kw,
                                subject,
                                self.match_pattern_cairo(&arm.pattern.node)
                            ));
                        }
                    }
                    for s in &arm.body {
                        out.push_str(&format!(
                            "        {};\n",
                            self.stmt_to_cairo(&s.node, params, fields)
                        ));
                    }
                    out.push_str("    }");
                }
                out
            }
            Statement::IndexedAssign { .. } | Statement::IndexedCompoundAssign { .. } => {
                "/* indexed ops unsupported in cairo target */".to_string()
            }
        }
    }

    fn match_pattern_cairo(&self, p: &MatchPattern) -> String {
        match p {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{}::{}", enum_name, variant)
            }
            MatchPattern::IntLit(v) => v.to_string(),
            MatchPattern::BoolLit(v) => v.to_string(),
            MatchPattern::StringLit(v) => format!("'{}'", v),
            MatchPattern::Wildcard => "_".to_string(),
        }
    }
}
