use std::collections::{HashMap, HashSet};

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct GoTarget;

impl CodeTarget for GoTarget {
    fn name(&self) -> &str {
        "go"
    }

    fn file_extension(&self) -> &str {
        "go"
    }

    fn generate(&self, program: &Program) -> String {
        let mut output = String::new();
        output.push_str("// Code generated by Verun. DO NOT EDIT.\n\n");
        output.push_str("package generated\n\n");
        output.push_str("func abs(x int64) int64 { if x < 0 { return -x }; return x }\n");
        output.push_str("func min(a int64, b int64) int64 { if a < b { return a }; return b }\n");
        output.push_str("func max(a int64, b int64) int64 { if a > b { return a }; return b }\n\n");

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => output.push_str(&self.gen_const(c)),
                Item::EnumDef(e) => output.push_str(&self.gen_enum(e)),
                Item::TypeDef(t) => output.push_str(&self.gen_type_def(t)),
                Item::State(s) => output.push_str(&self.gen_state(s)),
                _ => {}
            }
        }

        output
    }
}

impl GoTarget {
    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "const {} {} = {}\n\n",
            c.name.node,
            self.type_to_go(&c.ty.node),
            self.expr_to_go(&c.value.node, &HashSet::new(), &HashSet::new(), false)
        )
    }

    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = String::new();
        out.push_str(&format!("type {} int\n\n", e.name.node));
        out.push_str("const (\n");
        for (idx, variant) in e.variants.iter().enumerate() {
            if idx == 0 {
                out.push_str(&format!(
                    "\t{}_{} {} = iota\n",
                    e.name.node, variant.node, e.name.node
                ));
            } else {
                out.push_str(&format!("\t{}_{}\n", e.name.node, variant.node));
            }
        }
        out.push_str(")\n\n");
        out
    }

    fn gen_type_def(&self, t: &crate::ast::types::TypeDef) -> String {
        if let Some(alias_ty) = &t.alias {
            return format!(
                "type {} = {}\n\n",
                t.name.node,
                self.type_to_go(&alias_ty.node)
            );
        }
        let mut out = String::new();
        out.push_str(&format!("type {} struct {{\n", t.name.node));
        for field in &t.fields {
            out.push_str(&format!(
                "\t{} {}\n",
                self.go_field_name(&field.name.node),
                self.type_to_go(&field.ty.node)
            ));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_state(&self, state: &StateDef) -> String {
        let mut out = String::new();
        let field_types: HashMap<String, Type> = state
            .fields
            .iter()
            .map(|f| (f.name.node.clone(), f.ty.node.clone()))
            .collect();

        for c in &state.constants {
            out.push_str(&self.gen_const(c));
        }

        out.push_str(&format!("type {} struct {{\n", state.name.node));
        for field in &state.fields {
            out.push_str(&format!(
                "\t{} {}\n",
                self.go_field_name(&field.name.node),
                self.type_to_go(&field.ty.node)
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!(
            "func New{}() *{} {{\n",
            state.name.node, state.name.node
        ));
        out.push_str(&format!("\ts := &{}{{}}\n", state.name.node));
        if let Some(init) = &state.init {
            let assigned: HashSet<&str> = init
                .assignments
                .iter()
                .map(|a| a.target.node.as_str())
                .collect();
            for assign in &init.assignments {
                out.push_str(&format!(
                    "\ts.{} = {}\n",
                    self.go_field_name(&assign.target.node),
                    self.expr_to_go(&assign.value.node, &HashSet::new(), &HashSet::new(), false)
                ));
            }
            for field in &state.fields {
                if !assigned.contains(field.name.node.as_str())
                    && let Some(default) = self.default_for_go_type(&field.ty.node)
                {
                    out.push_str(&format!(
                        "\ts.{} = {}\n",
                        self.go_field_name(&field.name.node),
                        default
                    ));
                }
            }
        } else {
            for field in &state.fields {
                if let Some(default) = self.default_for_go_type(&field.ty.node) {
                    out.push_str(&format!(
                        "\ts.{} = {}\n",
                        self.go_field_name(&field.name.node),
                        default
                    ));
                }
            }
        }
        out.push_str("\treturn s\n}\n\n");

        for transition in &state.transitions {
            out.push_str(&self.gen_transition(state, transition, &field_types));
        }

        out
    }

    fn gen_transition(
        &self,
        state: &StateDef,
        t: &Transition,
        field_types: &HashMap<String, Type>,
    ) -> String {
        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{} {}", p.name.node, self.type_to_go(&p.ty.node)))
            .collect();
        let params_set: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let field_set: HashSet<String> = state.fields.iter().map(|f| f.name.node.clone()).collect();

        let mut out = String::new();
        out.push_str(&format!(
            "func (s *{}) {}({}) {{\n",
            state.name.node,
            self.go_field_name(&t.name.node),
            params.join(", ")
        ));

        for pre in &t.preconditions {
            out.push_str(&format!(
                "\tif !({}) {{ panic(\"precondition failed\") }}\n",
                self.expr_to_go(&pre.node, &params_set, &field_set, false)
            ));
        }

        if t.postconditions
            .iter()
            .any(|p| self.expr_contains_old(&p.node))
        {
            let old_fields: HashSet<String> = t
                .postconditions
                .iter()
                .flat_map(|p| self.fields_in_old(&p.node, &field_set))
                .collect();
            for field in &state.fields {
                if old_fields.contains(&field.name.node) {
                    out.push_str(&format!(
                        "\t_old_{} := s.{}\n",
                        field.name.node,
                        self.go_field_name(&field.name.node)
                    ));
                }
            }
        }

        for stmt in &t.body {
            let stmt_code = self.stmt_to_go(&stmt.node, &params_set, &field_set, field_types);
            if !stmt_code.is_empty() {
                out.push_str(&format!("\t{}\n", stmt_code));
            }
        }

        for inv in &state.invariants {
            let name = inv
                .name
                .as_ref()
                .map(|n| n.node.as_str())
                .unwrap_or("invariant");
            out.push_str(&format!(
                "\tif !({}) {{ panic(\"invariant '{}' violated\") }}\n",
                self.expr_to_go(&inv.condition.node, &params_set, &field_set, false),
                name
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "\tif !({}) {{ panic(\"postcondition violated\") }}\n",
                self.expr_to_go(&post.node, &params_set, &field_set, false)
            ));
        }

        out.push_str("}\n\n");
        out
    }

    fn type_to_go(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "int64".to_string(),
            Type::Real => "float64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "string".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, size } => format!("[{}]{}", size, self.type_to_go(element)),
            Type::Map { key, value } => {
                format!("map[{}]{}", self.type_to_go(key), self.type_to_go(value))
            }
        }
    }

    fn expr_to_go(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => v.to_string(),
            Expr::RealLit(v) => v.to_string(),
            Expr::BoolLit(v) => v.to_string(),
            Expr::StringLit(v) => format!("\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("s.{}", self.go_field_name(name))
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_go(&inner.node, params, fields, true),
            Expr::EnumVariant { enum_name, variant } => format!("{}_{}", enum_name, variant),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_go(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_go(&left.node, params, fields, in_old);
                let r = self.expr_to_go(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("((!{}) || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_go(&object.node, params, fields, in_old),
                    self.go_field_name(&field.node)
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[{}]",
                    self.expr_to_go(&object.node, params, fields, in_old),
                    self.expr_to_go(&index.node, params, fields, in_old)
                )
            }
            Expr::MapAccess { map, key } => {
                format!(
                    "{}[{}]",
                    self.expr_to_go(&map.node, params, fields, in_old),
                    self.expr_to_go(&key.node, params, fields, in_old)
                )
            }
            Expr::Forall { var, domain, body } => {
                self.quantifier_to_go(var, domain, body, params, fields, in_old, true)
            }
            Expr::Exists { var, domain, body } => {
                self.quantifier_to_go(var, domain, body, params, fields, in_old, false)
            }
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_go(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("abs({})", arg_strs[0]),
                    "min" => format!("min({}, {})", arg_strs[0], arg_strs[1]),
                    "max" => format!("max({}, {})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "/* unsupported */".to_string(),
        }
    }

    fn stmt_to_go(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        field_types: &HashMap<String, Type>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => {
                if let Expr::Ident(name) = &assign.value.node
                    && *name == assign.target.node
                {
                    return String::new();
                }
                format!(
                    "s.{} = {}",
                    self.go_field_name(&assign.target.node),
                    self.expr_to_go(&assign.value.node, params, fields, false)
                )
            }
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "s.{} {} {}",
                    self.go_field_name(&target.node),
                    op_str,
                    self.expr_to_go(&value.node, params, fields, false)
                )
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => {
                let target_name = self.go_field_name(&target.node);
                let index_s = self.expr_to_go(&index.node, params, fields, false);
                let value_s = self.expr_to_go(&value.node, params, fields, false);
                let _ = field_types;
                format!("s.{}[{}] = {}", target_name, index_s, value_s)
            }
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let op_str = match op {
                    CompoundOp::Add => "+",
                    CompoundOp::Sub => "-",
                    CompoundOp::Mul => "*",
                    CompoundOp::Div => "/",
                };
                let target_name = self.go_field_name(&target.node);
                let index_s = self.expr_to_go(&index.node, params, fields, false);
                let value_s = self.expr_to_go(&value.node, params, fields, false);
                format!(
                    "s.{}[{}] = s.{}[{}] {} {}",
                    target_name, index_s, target_name, index_s, op_str, value_s
                )
            }
            Statement::Assert { condition } => format!(
                "if !({}) {{ panic(\"assertion failed\") }}",
                self.expr_to_go(&condition.node, params, fields, false)
            ),
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut out = format!(
                    "if {} {{\n",
                    self.expr_to_go(&condition.node, params, fields, false)
                );
                for s in then_body {
                    let stmt_code = self.stmt_to_go(&s.node, params, fields, field_types);
                    if !stmt_code.is_empty() {
                        out.push_str(&format!("\t\t{}\n", stmt_code));
                    }
                }
                out.push('\t');
                out.push('}');
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        let stmt_code = self.stmt_to_go(&s.node, params, fields, field_types);
                        if !stmt_code.is_empty() {
                            out.push_str(&format!("\t\t{}\n", stmt_code));
                        }
                    }
                    out.push('\t');
                    out.push('}');
                }
                out
            }
            Statement::Let { name, value, .. } => format!(
                "{} := {}\n\t_ = {}",
                name.node,
                self.expr_to_go(&value.node, params, fields, false),
                name.node
            ),
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_go(&expr.node, params, fields, false);
                let mut out = format!("switch {} {{\n", subject);
                for arm in arms {
                    match &arm.pattern.node {
                        MatchPattern::Wildcard => out.push_str("\tdefault:\n"),
                        _ => out.push_str(&format!(
                            "\tcase {}:\n",
                            self.match_pattern_to_go(&arm.pattern.node)
                        )),
                    }
                    for s in &arm.body {
                        let stmt_code = self.stmt_to_go(&s.node, params, fields, field_types);
                        if !stmt_code.is_empty() {
                            out.push_str(&format!("\t\t{}\n", stmt_code));
                        }
                    }
                }
                out.push('\t');
                out.push('}');
                out
            }
        }
    }

    fn match_pattern_to_go(&self, pattern: &MatchPattern) -> String {
        match pattern {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{}_{}", enum_name, variant)
            }
            MatchPattern::IntLit(v) => v.to_string(),
            MatchPattern::BoolLit(v) => v.to_string(),
            MatchPattern::StringLit(v) => format!("\"{}\"", v),
            MatchPattern::Wildcard => "default".to_string(),
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn quantifier_to_go(
        &self,
        var: &crate::ast::span::Spanned<String>,
        domain: &crate::ast::span::Spanned<Expr>,
        body: &crate::ast::span::Spanned<Expr>,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
        is_forall: bool,
    ) -> String {
        if let Expr::Range { start, end } = &domain.node {
            let start_s = self.expr_to_go(&start.node, params, fields, in_old);
            let end_s = self.expr_to_go(&end.node, params, fields, in_old);
            let mut local_params = params.clone();
            local_params.insert(var.node.clone());
            let body_s = self.expr_to_go(&body.node, &local_params, fields, in_old);

            if is_forall {
                format!(
                    "func() bool {{ for {} := int64({}); {} < int64({}); {}++ {{ if !({}) {{ return false }} }}; return true }}()",
                    var.node, start_s, var.node, end_s, var.node, body_s
                )
            } else {
                format!(
                    "func() bool {{ for {} := int64({}); {} < int64({}); {}++ {{ if ({}) {{ return true }} }}; return false }}()",
                    var.node, start_s, var.node, end_s, var.node, body_s
                )
            }
        } else if is_forall {
            "true".to_string()
        } else {
            "false".to_string()
        }
    }

    fn fields_in_old(&self, expr: &Expr, field_set: &HashSet<String>) -> HashSet<String> {
        match expr {
            Expr::Old(inner) => {
                let mut set = HashSet::new();
                self.collect_field_idents(&inner.node, field_set, &mut set);
                set
            }
            Expr::BinaryOp { left, right, .. } => {
                let mut s = self.fields_in_old(&left.node, field_set);
                s.extend(self.fields_in_old(&right.node, field_set));
                s
            }
            Expr::UnaryOp { operand, .. } => self.fields_in_old(&operand.node, field_set),
            Expr::FnCall { args, .. } => args
                .iter()
                .flat_map(|a| self.fields_in_old(&a.node, field_set))
                .collect(),
            Expr::FieldAccess { object, .. } => self.fields_in_old(&object.node, field_set),
            Expr::IndexAccess { object, index } => {
                let mut s = self.fields_in_old(&object.node, field_set);
                s.extend(self.fields_in_old(&index.node, field_set));
                s
            }
            Expr::MapAccess { map, key } => {
                let mut s = self.fields_in_old(&map.node, field_set);
                s.extend(self.fields_in_old(&key.node, field_set));
                s
            }
            _ => HashSet::new(),
        }
    }

    fn collect_field_idents(
        &self,
        expr: &Expr,
        field_set: &HashSet<String>,
        result: &mut HashSet<String>,
    ) {
        match expr {
            Expr::Ident(name) if field_set.contains(name) => {
                result.insert(name.clone());
            }
            Expr::BinaryOp { left, right, .. } => {
                self.collect_field_idents(&left.node, field_set, result);
                self.collect_field_idents(&right.node, field_set, result);
            }
            Expr::UnaryOp { operand, .. } => {
                self.collect_field_idents(&operand.node, field_set, result);
            }
            Expr::IndexAccess { object, index } => {
                self.collect_field_idents(&object.node, field_set, result);
                self.collect_field_idents(&index.node, field_set, result);
            }
            Expr::FieldAccess { object, .. } => {
                self.collect_field_idents(&object.node, field_set, result);
            }
            Expr::FnCall { args, .. } => {
                for a in args {
                    self.collect_field_idents(&a.node, field_set, result);
                }
            }
            _ => {}
        }
    }

    fn go_field_name(&self, name: &str) -> String {
        let mut chars = name.chars();
        match chars.next() {
            Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
            None => String::new(),
        }
    }

    fn default_for_go_type(&self, ty: &Type) -> Option<String> {
        match ty {
            Type::Map { key, value } => Some(format!(
                "make(map[{}]{})",
                self.type_to_go(key),
                self.type_to_go(value)
            )),
            _ => None,
        }
    }

    fn expr_contains_old(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Old(_) => true,
            Expr::UnaryOp { operand, .. } => self.expr_contains_old(&operand.node),
            Expr::BinaryOp { left, right, .. } => {
                self.expr_contains_old(&left.node) || self.expr_contains_old(&right.node)
            }
            Expr::FieldAccess { object, .. } => self.expr_contains_old(&object.node),
            Expr::IndexAccess { object, index } => {
                self.expr_contains_old(&object.node) || self.expr_contains_old(&index.node)
            }
            Expr::MapAccess { map, key } => {
                self.expr_contains_old(&map.node) || self.expr_contains_old(&key.node)
            }
            Expr::FnCall { args, .. } => args.iter().any(|a| self.expr_contains_old(&a.node)),
            _ => false,
        }
    }
}
