use std::collections::{HashMap, HashSet};

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct JavaTarget;

impl CodeTarget for JavaTarget {
    fn name(&self) -> &str {
        "java"
    }

    fn file_extension(&self) -> &str {
        "java"
    }

    fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("// Generated by Verun.\n\n");

        let type_aliases: HashMap<String, Type> = program
            .items
            .iter()
            .filter_map(|i| match &i.node {
                Item::TypeDef(t) => t.alias.as_ref().map(|alias| (t.name.node.clone(), alias.node.clone())),
                _ => None,
            })
            .collect();

        let top_consts: Vec<&ConstDef> = program
            .items
            .iter()
            .filter_map(|i| match &i.node {
                Item::ConstDef(c) => Some(c),
                _ => None,
            })
            .collect();
        let top_const_names: HashSet<String> =
            top_consts.iter().map(|c| c.name.node.clone()).collect();
        if !top_consts.is_empty() {
            out.push_str("final class VerunConsts {\n");
            for c in top_consts {
                out.push_str(&format!(
                    "    static final {} {} = {};\n",
                    self.type_to_java(&c.ty.node, &type_aliases),
                    c.name.node,
                    self.expr_to_java(
                        &c.value.node,
                        &HashSet::new(),
                        &HashSet::new(),
                        &top_const_names,
                        false,
                    )
                ));
            }
            out.push_str("}\n\n");
        }

        for item in &program.items {
            match &item.node {
                Item::EnumDef(e) => out.push_str(&self.gen_enum(e)),
                Item::TypeDef(t) => out.push_str(&self.gen_type_def(t, &type_aliases)),
                Item::State(s) => out.push_str(&self.gen_state(s, &top_const_names, &type_aliases)),
                _ => {}
            }
        }

        out
    }
}

impl JavaTarget {
    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = format!("enum {} {{\n", e.name.node);
        for (i, variant) in e.variants.iter().enumerate() {
            if i + 1 == e.variants.len() {
                out.push_str(&format!("    {}\n", variant.node));
            } else {
                out.push_str(&format!("    {},\n", variant.node));
            }
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_type_def(
        &self,
        t: &crate::ast::types::TypeDef,
        type_aliases: &HashMap<String, Type>,
    ) -> String {
        // Java has no type aliases; for refinement types, skip (base type is used inline)
        if t.alias.is_some() {
            return String::new();
        }
        let mut out = format!("class {} {{\n", t.name.node);
        for field in &t.fields {
            out.push_str(&format!(
                "    public {} {};\n",
                self.type_to_java(&field.ty.node, type_aliases),
                field.name.node
            ));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_state(
        &self,
        state: &StateDef,
        top_consts: &HashSet<String>,
        type_aliases: &HashMap<String, Type>,
    ) -> String {
        let mut out = format!("class {} {{\n", state.name.node);
        let field_types: HashMap<String, Type> = state
            .fields
            .iter()
            .map(|f| (f.name.node.clone(), f.ty.node.clone()))
            .collect();

        for c in &state.constants {
            out.push_str(&format!(
                "    public static final {} {} = {};\n",
                self.type_to_java(&c.ty.node, type_aliases),
                c.name.node,
                self.expr_to_java(
                    &c.value.node,
                    &HashSet::new(),
                    &HashSet::new(),
                    top_consts,
                    false
                )
            ));
        }
        if !state.constants.is_empty() {
            out.push('\n');
        }

        for field in &state.fields {
            out.push_str(&format!(
                "    public {} {};\n",
                self.type_to_java(&field.ty.node, type_aliases),
                field.name.node
            ));
        }
        out.push('\n');

        out.push_str(&format!("    public {}() {{\n", state.name.node));
        if let Some(init) = &state.init {
            let assigned: HashSet<&str> =
                init.assignments.iter().map(|a| a.target.node.as_str()).collect();
            for assign in &init.assignments {
                out.push_str(&format!(
                    "        this.{} = {};\n",
                    assign.target.node,
                    self.expr_to_java(
                        &assign.value.node,
                        &HashSet::new(),
                        &HashSet::new(),
                        top_consts,
                        false
                    )
                ));
            }
            for field in &state.fields {
                if !assigned.contains(field.name.node.as_str())
                    && let Some(default) =
                        self.java_default_for_type(&field.ty.node, type_aliases)
                {
                    out.push_str(&format!(
                        "        this.{} = {};\n",
                        field.name.node, default
                    ));
                }
            }
        }
        out.push_str("    }\n\n");

        for transition in &state.transitions {
            out.push_str(&self.gen_transition(state, transition, top_consts, type_aliases, &field_types));
        }

        out.push_str("}\n\n");
        out
    }

    fn gen_transition(
        &self,
        state: &StateDef,
        t: &Transition,
        top_consts: &HashSet<String>,
        type_aliases: &HashMap<String, Type>,
        field_types: &HashMap<String, Type>,
    ) -> String {
        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{} {}", self.type_to_java(&p.ty.node, type_aliases), p.name.node))
            .collect();
        let params_set: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let fields_set: HashSet<String> =
            state.fields.iter().map(|f| f.name.node.clone()).collect();

        let mut out = format!(
            "    public void {}({}) {{\n",
            t.name.node,
            params.join(", ")
        );

        for pre in &t.preconditions {
            out.push_str(&format!(
                "        if (!({})) throw new RuntimeException(\"precondition failed\");\n",
                self.expr_to_java(&pre.node, &params_set, &fields_set, top_consts, false)
            ));
        }

        if !t.postconditions.is_empty() {
            for field in &state.fields {
                out.push_str(&format!(
                    "        var _old_{} = this.{};\n",
                    field.name.node, field.name.node
                ));
            }
        }

        for stmt in &t.body {
            let stmt_code = self.stmt_to_java(
                &stmt.node,
                &params_set,
                &fields_set,
                top_consts,
                type_aliases,
                field_types,
            );
            if !stmt_code.is_empty() {
                if self.is_block_statement(&stmt.node) {
                    out.push_str(&format!("        {}\n", stmt_code));
                } else {
                    out.push_str(&format!("        {};\n", stmt_code));
                }
            }
        }

        for inv in &state.invariants {
            let inv_name = inv
                .name
                .as_ref()
                .map(|n| n.node.as_str())
                .unwrap_or("invariant");
            out.push_str(&format!(
                "        if (!({})) throw new RuntimeException(\"invariant '{}' violated\");\n",
                self.expr_to_java(
                    &inv.condition.node,
                    &params_set,
                    &fields_set,
                    top_consts,
                    false
                ),
                inv_name
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "        if (!({})) throw new RuntimeException(\"postcondition violated\");\n",
                self.expr_to_java(&post.node, &params_set, &fields_set, top_consts, false)
            ));
        }

        out.push_str("    }\n\n");
        out
    }

    fn type_to_java(&self, ty: &Type, type_aliases: &HashMap<String, Type>) -> String {
        match self.resolve_java_alias(ty, type_aliases) {
            Type::Int => "long".to_string(),
            Type::Real => "double".to_string(),
            Type::Bool => "boolean".to_string(),
            Type::String => "String".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, size: _ } => format!("{}[]", self.type_to_java(element, type_aliases)),
            Type::Map { key, value } => format!(
                "java.util.Map<{}, {}>",
                self.boxed_java_type(key, type_aliases),
                self.boxed_java_type(value, type_aliases)
            ),
        }
    }

    fn boxed_java_type(&self, ty: &Type, type_aliases: &HashMap<String, Type>) -> String {
        match self.resolve_java_alias(ty, type_aliases) {
            Type::Int => "Long".to_string(),
            Type::Real => "Double".to_string(),
            Type::Bool => "Boolean".to_string(),
            Type::String => "String".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, .. } => format!("{}[]", self.boxed_java_type(element, type_aliases)),
            Type::Map { key, value } => format!(
                "java.util.Map<{}, {}>",
                self.boxed_java_type(key, type_aliases),
                self.boxed_java_type(value, type_aliases)
            ),
        }
    }

    fn expr_to_java(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        top_consts: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => v.to_string(),
            Expr::RealLit(v) => v.to_string(),
            Expr::BoolLit(v) => v.to_string(),
            Expr::StringLit(v) => format!("\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("this.{}", name)
                } else if top_consts.contains(name) {
                    format!("VerunConsts.{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_java(&inner.node, params, fields, top_consts, true),
            Expr::EnumVariant { enum_name, variant } => format!("{}.{}", enum_name, variant),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_java(&operand.node, params, fields, top_consts, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_java(&left.node, params, fields, top_consts, in_old);
                let r = self.expr_to_java(&right.node, params, fields, top_consts, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("((!{}) || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_java(&object.node, params, fields, top_consts, in_old),
                    field.node
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[(int)({})]" ,
                    self.expr_to_java(&object.node, params, fields, top_consts, in_old),
                    self.expr_to_java(&index.node, params, fields, top_consts, in_old)
                )
            }
            Expr::MapAccess { map, key } => {
                format!(
                    "{}.get({})",
                    self.expr_to_java(&map.node, params, fields, top_consts, in_old),
                    self.expr_to_java(&key.node, params, fields, top_consts, in_old)
                )
            }
            Expr::Forall { var, domain, body } => {
                self.quantifier_to_java(var, domain, body, params, fields, top_consts, in_old, true)
            }
            Expr::Exists { var, domain, body } => {
                self.quantifier_to_java(var, domain, body, params, fields, top_consts, in_old, false)
            }
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_java(&a.node, params, fields, top_consts, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("Math.abs({})", arg_strs[0]),
                    "min" => format!("Math.min({}, {})", arg_strs[0], arg_strs[1]),
                    "max" => format!("Math.max({}, {})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "/* unsupported */".to_string(),
        }
    }

    fn stmt_to_java(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        top_consts: &HashSet<String>,
        type_aliases: &HashMap<String, Type>,
        field_types: &HashMap<String, Type>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => {
                if let Expr::Ident(name) = &assign.value.node
                    && *name == assign.target.node
                {
                    return String::new();
                }
                format!(
                    "this.{} = {}",
                    assign.target.node,
                    self.expr_to_java(&assign.value.node, params, fields, top_consts, false)
                )
            }
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "this.{} {} {}",
                    target.node,
                    op_str,
                    self.expr_to_java(&value.node, params, fields, top_consts, false)
                )
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => {
                let index_s = self.expr_to_java(&index.node, params, fields, top_consts, false);
                let value_s = self.expr_to_java(&value.node, params, fields, top_consts, false);
                if matches!(field_types.get(&target.node), Some(Type::Map { .. })) {
                    format!("this.{}.put({}, {})", target.node, index_s, value_s)
                } else {
                    format!("this.{}[(int)({})] = {}", target.node, index_s, value_s)
                }
            }
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let op_str = match op {
                    CompoundOp::Add => "+",
                    CompoundOp::Sub => "-",
                    CompoundOp::Mul => "*",
                    CompoundOp::Div => "/",
                };
                let index_s = self.expr_to_java(&index.node, params, fields, top_consts, false);
                let value_s = self.expr_to_java(&value.node, params, fields, top_consts, false);
                if let Some(Type::Map { value: map_value, .. }) = field_types.get(&target.node) {
                    let default_s = self.java_zero_value(map_value, type_aliases);
                    format!(
                        "this.{}.put({}, this.{}.getOrDefault({}, {}) {} {})",
                        target.node, index_s, target.node, index_s, default_s, op_str, value_s
                    )
                } else {
                    format!(
                        "this.{}[(int)({})] {}= {}",
                        target.node, index_s, op_str, value_s
                    )
                }
            }
            Statement::Assert { condition } => format!(
                "if (!({})) throw new RuntimeException(\"assertion failed\")",
                self.expr_to_java(&condition.node, params, fields, top_consts, false)
            ),
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut out = format!(
                    "if ({}) {{\n",
                    self.expr_to_java(&condition.node, params, fields, top_consts, false)
                );
                for s in then_body {
                    let stmt_code = self.stmt_to_java(
                        &s.node,
                        params,
                        fields,
                        top_consts,
                        type_aliases,
                        field_types,
                    );
                    if !stmt_code.is_empty() {
                        if self.is_block_statement(&s.node) {
                            out.push_str(&format!("            {}\n", stmt_code));
                        } else {
                            out.push_str(&format!("            {};\n", stmt_code));
                        }
                    }
                }
                out.push_str("        }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        let stmt_code = self.stmt_to_java(
                            &s.node,
                            params,
                            fields,
                            top_consts,
                            type_aliases,
                            field_types,
                        );
                        if !stmt_code.is_empty() {
                            if self.is_block_statement(&s.node) {
                                out.push_str(&format!("            {}\n", stmt_code));
                            } else {
                                out.push_str(&format!("            {};\n", stmt_code));
                            }
                        }
                    }
                    out.push_str("        }");
                }
                out
            }
            Statement::Let { name, ty, value } => {
                let declared = ty
                    .as_ref()
                    .map(|t| self.type_to_java(&t.node, type_aliases))
                    .unwrap_or_else(|| "var".to_string());
                format!(
                    "{} {} = {}",
                    declared,
                    name.node,
                    self.expr_to_java(&value.node, params, fields, top_consts, false)
                )
            }
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_java(&expr.node, params, fields, top_consts, false);
                let mut out = format!("switch ({}) {{\n", subject);
                for arm in arms {
                    match &arm.pattern.node {
                        MatchPattern::Wildcard => out.push_str("            default:\n"),
                        _ => out.push_str(&format!(
                            "            case {}:\n",
                            self.match_pattern_java(&arm.pattern.node)
                        )),
                    }
                    for s in &arm.body {
                        let stmt_code = self.stmt_to_java(
                            &s.node,
                            params,
                            fields,
                            top_consts,
                            type_aliases,
                            field_types,
                        );
                        if !stmt_code.is_empty() {
                            if self.is_block_statement(&s.node) {
                                out.push_str(&format!("                {}\n", stmt_code));
                            } else {
                                out.push_str(&format!("                {};\n", stmt_code));
                            }
                        }
                    }
                    out.push_str("                break;\n");
                }
                out.push_str("        }");
                out
            }
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn quantifier_to_java(
        &self,
        var: &crate::ast::span::Spanned<String>,
        domain: &crate::ast::span::Spanned<Expr>,
        body: &crate::ast::span::Spanned<Expr>,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        top_consts: &HashSet<String>,
        in_old: bool,
        is_forall: bool,
    ) -> String {
        if let Expr::Range { start, end } = &domain.node {
            let start_s = self.expr_to_java(&start.node, params, fields, top_consts, in_old);
            let end_s = self.expr_to_java(&end.node, params, fields, top_consts, in_old);
            let mut local_params = params.clone();
            local_params.insert(var.node.clone());
            let body_s = self.expr_to_java(&body.node, &local_params, fields, top_consts, in_old);

            if is_forall {
                format!(
                    "java.util.stream.IntStream.range((int)({}), (int)({})).allMatch({} -> ({}))",
                    start_s, end_s, var.node, body_s
                )
            } else {
                format!(
                    "java.util.stream.IntStream.range((int)({}), (int)({})).anyMatch({} -> ({}))",
                    start_s, end_s, var.node, body_s
                )
            }
        } else if is_forall {
            "true".to_string()
        } else {
            "false".to_string()
        }
    }

    fn java_default_for_type(
        &self,
        ty: &Type,
        type_aliases: &HashMap<String, Type>,
    ) -> Option<String> {
        match self.resolve_java_alias(ty, type_aliases) {
            Type::Array { element, size } => {
                Some(format!("new {}[{}]", self.java_primitive_element(element, type_aliases), size))
            }
            Type::Map { key, value } => Some(format!(
                "new java.util.HashMap<{}, {}>()",
                self.boxed_java_type(key, type_aliases),
                self.boxed_java_type(value, type_aliases)
            )),
            _ => None,
        }
    }

    fn java_primitive_element(&self, ty: &Type, type_aliases: &HashMap<String, Type>) -> String {
        match self.resolve_java_alias(ty, type_aliases) {
            Type::Int => "long".to_string(),
            Type::Real => "double".to_string(),
            Type::Bool => "boolean".to_string(),
            _ => self.type_to_java(ty, type_aliases),
        }
    }

    fn resolve_java_alias<'a>(
        &self,
        ty: &'a Type,
        type_aliases: &'a HashMap<String, Type>,
    ) -> &'a Type {
        match ty {
            Type::Named(name) => type_aliases
                .get(name)
                .map(|alias| self.resolve_java_alias(alias, type_aliases))
                .unwrap_or(ty),
            _ => ty,
        }
    }

    fn java_zero_value(&self, ty: &Type, type_aliases: &HashMap<String, Type>) -> String {
        match self.resolve_java_alias(ty, type_aliases) {
            Type::Int => "0L".to_string(),
            Type::Real => "0.0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "\"\"".to_string(),
            Type::Enum(name) => format!("{}.values()[0]", name),
            _ => "null".to_string(),
        }
    }

    fn is_block_statement(&self, stmt: &Statement) -> bool {
        matches!(stmt, Statement::If { .. } | Statement::Match { .. })
    }

    fn match_pattern_java(&self, p: &MatchPattern) -> String {
        match p {
            MatchPattern::EnumVariant {
                enum_name: _,
                variant,
            } => variant.clone(),
            MatchPattern::IntLit(v) => v.to_string(),
            MatchPattern::BoolLit(v) => v.to_string(),
            MatchPattern::StringLit(v) => format!("\"{}\"", v),
            MatchPattern::Wildcard => "default".to_string(),
        }
    }
}
