use std::collections::HashSet;

use crate::ast::nodes::*;

use super::target::CodeTarget;

pub struct MoveTarget;

impl CodeTarget for MoveTarget {
    fn name(&self) -> &str {
        "move"
    }

    fn file_extension(&self) -> &str {
        "move"
    }

    fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("// Generated by Verun\n");
        out.push_str("module verun::generated {\n\n");

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => {
                    out.push_str(&format!(
                        "    const {}: {} = {};\n",
                        c.name.node,
                        self.type_to_move(&c.ty.node),
                        self.expr_to_move(&c.value.node, &HashSet::new(), &HashSet::new(), false)
                    ));
                }
                Item::EnumDef(e) => {
                    out.push_str(&format!("    // enum {}\n", e.name.node));
                    out.push_str(&format!("    type {} = u64;\n", e.name.node));
                    for (idx, variant) in e.variants.iter().enumerate() {
                        out.push_str(&format!(
                            "    const {}_{}: u64 = {};\n",
                            e.name.node.to_uppercase(),
                            variant.node.to_uppercase(),
                            idx
                        ));
                    }
                    out.push('\n');
                }
                _ => {}
            }
        }

        for item in &program.items {
            if let Item::State(state) = &item.node {
                out.push_str(&self.gen_state(state));
            }
        }

        out.push_str("}\n");
        out
    }
}

impl MoveTarget {
    fn gen_state(&self, state: &StateDef) -> String {
        let mut out = String::new();

        for c in &state.constants {
            out.push_str(&format!(
                "    const {}: {} = {};\n",
                c.name.node,
                self.type_to_move(&c.ty.node),
                self.expr_to_move(&c.value.node, &HashSet::new(), &HashSet::new(), false)
            ));
        }
        if !state.constants.is_empty() {
            out.push('\n');
        }

        out.push_str(&format!("    struct {} has key {{\n", state.name.node));
        for field in &state.fields {
            out.push_str(&format!(
                "        {}: {},\n",
                field.name.node,
                self.type_to_move(&field.ty.node)
            ));
        }
        out.push_str("    }\n\n");

        out.push_str(&format!(
            "    public fun init_{}(): {} {{\n",
            state.name.node.to_lowercase(),
            state.name.node
        ));
        out.push_str(&format!("        let s = {} {{\n", state.name.node));
        for (idx, field) in state.fields.iter().enumerate() {
            let mut initialized = "0".to_string();
            if let Some(init) = &state.init
                && let Some(assign) = init
                    .assignments
                    .iter()
                    .find(|a| a.target.node == field.name.node)
            {
                initialized =
                    self.expr_to_move(&assign.value.node, &HashSet::new(), &HashSet::new(), false);
            }
            let trailing = if idx + 1 == state.fields.len() {
                ""
            } else {
                ","
            };
            out.push_str(&format!(
                "            {}: {}{}\n",
                field.name.node, initialized, trailing
            ));
        }
        out.push_str("        };\n");
        out.push_str("        s\n");
        out.push_str("    }\n\n");

        for t in &state.transitions {
            out.push_str(&self.gen_transition(state, t));
        }

        out
    }

    fn gen_transition(&self, state: &StateDef, t: &Transition) -> String {
        let mut params = vec![format!("s: &mut {}", state.name.node)];
        params.extend(
            t.params
                .iter()
                .map(|p| format!("{}: {}", p.name.node, self.type_to_move(&p.ty.node))),
        );

        let param_set: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let field_set: HashSet<String> = state.fields.iter().map(|f| f.name.node.clone()).collect();

        let mut out = format!("    public fun {}({}) {{\n", t.name.node, params.join(", "));

        for pre in &t.preconditions {
            out.push_str(&format!(
                "        assert!({}, 100);\n",
                self.expr_to_move(&pre.node, &param_set, &field_set, false)
            ));
        }

        for stmt in &t.body {
            out.push_str(&format!(
                "        {};\n",
                self.stmt_to_move(&stmt.node, &param_set, &field_set)
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "        assert!({}, 200);\n",
                self.expr_to_move(&post.node, &param_set, &field_set, false)
            ));
        }

        out.push_str("    }\n\n");
        out
    }

    fn type_to_move(&self, ty: &crate::ast::types::Type) -> String {
        use crate::ast::types::Type;
        match ty {
            Type::Int => "u64".to_string(),
            Type::Real => "u64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "vector<u8>".to_string(),
            Type::Named(name) => name.clone(),
            Type::Enum(_) => "u64".to_string(),
            Type::Array { element, .. } => format!("vector<{}>", self.type_to_move(element)),
            Type::Map { key: _, value } => format!("vector<{}>", self.type_to_move(value)),
        }
    }

    fn expr_to_move(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => v.to_string(),
            Expr::RealLit(v) => format!("{}", *v as i64),
            Expr::BoolLit(v) => v.to_string(),
            Expr::StringLit(v) => format!("b\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("s.{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_move(&inner.node, params, fields, true),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_move(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("(0 - {})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_move(&left.node, params, fields, in_old);
                let r = self.expr_to_move(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("((!{}) || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::EnumVariant { enum_name, variant } => {
                format!("{}_{}", enum_name.to_uppercase(), variant.to_uppercase())
            }
            Expr::Forall { .. } => "true".to_string(),
            Expr::Exists { .. } => "false".to_string(),
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_move(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("if ({0} > 0) {{ {0} }} else {{ 0 - {0} }}", arg_strs[0]),
                    "min" => format!(
                        "if ({0} < {1}) {{ {0} }} else {{ {1} }}",
                        arg_strs[0], arg_strs[1]
                    ),
                    "max" => format!(
                        "if ({0} > {1}) {{ {0} }} else {{ {1} }}",
                        arg_strs[0], arg_strs[1]
                    ),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "0".to_string(),
        }
    }

    fn stmt_to_move(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => format!(
                "s.{} = {}",
                assign.target.node,
                self.expr_to_move(&assign.value.node, params, fields, false)
            ),
            Statement::CompoundAssign { target, op, value } => {
                let rhs = self.expr_to_move(&value.node, params, fields, false);
                match op {
                    CompoundOp::Add => format!("s.{0} = s.{0} + {1}", target.node, rhs),
                    CompoundOp::Sub => format!("s.{0} = s.{0} - {1}", target.node, rhs),
                    CompoundOp::Mul => format!("s.{0} = s.{0} * {1}", target.node, rhs),
                    CompoundOp::Div => format!("s.{0} = s.{0} / {1}", target.node, rhs),
                }
            }
            Statement::Assert { condition } => format!(
                "assert!({}, 300)",
                self.expr_to_move(&condition.node, params, fields, false)
            ),
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut out = format!(
                    "if ({}) {{\n",
                    self.expr_to_move(&condition.node, params, fields, false)
                );
                for s in then_body {
                    out.push_str(&format!(
                        "            {};\n",
                        self.stmt_to_move(&s.node, params, fields)
                    ));
                }
                out.push_str("        }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        out.push_str(&format!(
                            "            {};\n",
                            self.stmt_to_move(&s.node, params, fields)
                        ));
                    }
                    out.push_str("        }");
                }
                out
            }
            Statement::Let { name, value, .. } => format!(
                "let {} = {}",
                name.node,
                self.expr_to_move(&value.node, params, fields, false)
            ),
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_move(&expr.node, params, fields, false);
                let mut out = String::new();
                for (idx, arm) in arms.iter().enumerate() {
                    match &arm.pattern.node {
                        MatchPattern::Wildcard => out.push_str(" else {\n"),
                        _ => {
                            let kw = if idx == 0 { "if" } else { "else if" };
                            out.push_str(&format!(
                                "{} ({} == {}) {{\n",
                                kw,
                                subject,
                                self.match_pattern_to_move(&arm.pattern.node)
                            ));
                        }
                    }
                    for s in &arm.body {
                        out.push_str(&format!(
                            "            {};\n",
                            self.stmt_to_move(&s.node, params, fields)
                        ));
                    }
                    out.push_str("        }");
                }
                out
            }
            Statement::IndexedAssign { .. } | Statement::IndexedCompoundAssign { .. } => {
                "/* indexed ops unsupported in move target */".to_string()
            }
        }
    }

    fn match_pattern_to_move(&self, p: &MatchPattern) -> String {
        match p {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{}_{}", enum_name.to_uppercase(), variant.to_uppercase())
            }
            MatchPattern::IntLit(v) => v.to_string(),
            MatchPattern::BoolLit(v) => v.to_string(),
            MatchPattern::StringLit(v) => format!("b\"{}\"", v),
            MatchPattern::Wildcard => "_".to_string(),
        }
    }
}
