use std::collections::{HashMap, HashSet};

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct RustTarget;

impl CodeTarget for RustTarget {
    fn name(&self) -> &str {
        "rust"
    }

    fn file_extension(&self) -> &str {
        "rs"
    }

    fn generate(&self, program: &Program) -> String {
        let mut output = String::new();
        output.push_str("// Generated by Verun — do not edit manually\n\n");

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => output.push_str(&self.gen_const(c)),
                Item::EnumDef(e) => output.push_str(&self.gen_enum(e)),
                Item::TypeDef(t) => output.push_str(&self.gen_type_def(t)),
                Item::State(s) => output.push_str(&self.gen_state(s)),
                _ => {}
            }
        }

        output
    }
}

impl RustTarget {
    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "pub const {}: {} = {};\n\n",
            c.name.node,
            self.type_to_rust(&c.ty.node),
            self.expr_to_rust(&c.value.node, &HashSet::new(), &HashSet::new(), false)
        )
    }

    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n".to_string();
        out.push_str(&format!("pub enum {} {{\n", e.name.node));
        for variant in &e.variants {
            out.push_str(&format!("    {},\n", variant.node));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_type_def(&self, t: &crate::ast::types::TypeDef) -> String {
        if let Some(alias_ty) = &t.alias {
            return format!(
                "pub type {} = {};\n\n",
                t.name.node,
                self.type_to_rust(&alias_ty.node)
            );
        }
        let mut out = "#[derive(Debug, Clone)]\n".to_string();
        out.push_str(&format!("pub struct {} {{\n", t.name.node));
        for field in &t.fields {
            out.push_str(&format!(
                "    pub {}: {},\n",
                field.name.node,
                self.type_to_rust(&field.ty.node)
            ));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_state(&self, state: &StateDef) -> String {
        let mut out = String::new();

        for c in &state.constants {
            out.push_str(&self.gen_const(c));
        }

        out.push_str("#[derive(Debug, Clone)]\n");
        out.push_str(&format!("pub struct {} {{\n", state.name.node));
        for field in &state.fields {
            out.push_str(&format!(
                "    pub {}: {},\n",
                field.name.node,
                self.type_to_rust(&field.ty.node)
            ));
        }
        out.push_str("}\n\n");

        out.push_str(&format!("impl {} {{\n", state.name.node));

        if let Some(init) = &state.init {
            let assigned: HashSet<&str> =
                init.assignments.iter().map(|a| a.target.node.as_str()).collect();
            out.push_str("    pub fn new() -> Self {\n");
            out.push_str("        Self {\n");
            for assign in &init.assignments {
                out.push_str(&format!(
                    "            {}: {},\n",
                    assign.target.node,
                    self.expr_to_rust(&assign.value.node, &HashSet::new(), &HashSet::new(), false)
                ));
            }
            for field in &state.fields {
                if !assigned.contains(field.name.node.as_str()) {
                    out.push_str(&format!(
                        "            {}: {},\n",
                        field.name.node,
                        self.default_for_type(&field.ty.node)
                    ));
                }
            }
            out.push_str("        }\n");
            out.push_str("    }\n\n");
        }

        let field_types: HashMap<String, Type> = state
            .fields
            .iter()
            .map(|f| (f.name.node.clone(), f.ty.node.clone()))
            .collect();

        for transition in &state.transitions {
            out.push_str(&self.gen_transition(transition, state, &field_types));
        }

        out.push_str("}\n\n");
        out
    }

    fn gen_transition(
        &self,
        t: &Transition,
        state: &StateDef,
        field_types: &HashMap<String, Type>,
    ) -> String {
        let mut out = String::new();

        let param_names: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let field_names: HashSet<String> =
            state.fields.iter().map(|f| f.name.node.clone()).collect();

        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name.node, self.type_to_rust(&p.ty.node)))
            .collect();

        let param_str = if params.is_empty() {
            String::new()
        } else {
            format!(", {}", params.join(", "))
        };

        out.push_str(&format!(
            "    pub fn {}(&mut self{}) -> Result<(), String> {{\n",
            t.name.node, param_str
        ));

        for pre in &t.preconditions {
            out.push_str(&format!(
                "        if !({}) {{ return Err(\"precondition failed\".to_string()); }}\n",
                self.expr_to_rust(&pre.node, &param_names, &field_names, false)
            ));
        }

        if !t.postconditions.is_empty() {
            for field in &state.fields {
                out.push_str(&format!(
                    "        let _old_{} = self.{}.clone();\n",
                    field.name.node, field.name.node
                ));
            }
        }

        for stmt in &t.body {
            let stmt_code = self.stmt_to_rust(&stmt.node, &param_names, &field_names, field_types);
            if !stmt_code.is_empty() {
                out.push_str(&format!("        {};\n", stmt_code));
            }
        }

        for inv in &state.invariants {
            let inv_name = inv
                .name
                .as_ref()
                .map(|n| n.node.as_str())
                .unwrap_or("invariant");
            out.push_str(&format!(
                "        debug_assert!({}, \"invariant '{}' violated after '{}'\");\n",
                self.expr_to_rust(&inv.condition.node, &param_names, &field_names, false),
                inv_name,
                t.name.node
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "        debug_assert!({}, \"postcondition violated in '{}'\");\n",
                self.expr_to_rust(&post.node, &param_names, &field_names, false),
                t.name.node
            ));
        }

        out.push_str("        Ok(())\n");
        out.push_str("    }\n\n");
        out
    }

    fn type_to_rust(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "i64".to_string(),
            Type::Real => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String".to_string(),
            Type::Named(name) => name.clone(),
            Type::Enum(name) => name.clone(),
            Type::Array { element, size } => {
                format!("[{}; {}]", self.type_to_rust(element), size)
            }
            Type::Map { key, value } => {
                format!(
                    "std::collections::HashMap<{}, {}>",
                    self.type_to_rust(key),
                    self.type_to_rust(value)
                )
            }
        }
    }

    fn expr_to_rust(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => format!("{}", v),
            Expr::RealLit(v) => format!("{}", v),
            Expr::BoolLit(v) => format!("{}", v),
            Expr::StringLit(v) => format!("\"{}\".to_string()", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("self.{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_rust(&inner.node, params, fields, true),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_rust(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_rust(&left.node, params, fields, in_old);
                let r = self.expr_to_rust(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("(!{} || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::EnumVariant { enum_name, variant } => format!("{}::{}", enum_name, variant),
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_rust(&object.node, params, fields, in_old),
                    field.node
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[({}) as usize]",
                    self.expr_to_rust(&object.node, params, fields, in_old),
                    self.expr_to_rust(&index.node, params, fields, in_old)
                )
            }
            Expr::MapAccess { map, key } => {
                format!(
                    "{}[&{}]",
                    self.expr_to_rust(&map.node, params, fields, in_old),
                    self.expr_to_rust(&key.node, params, fields, in_old)
                )
            }
            Expr::Forall { var, domain, body } => {
                self.quantifier_to_rust(var, domain, body, params, fields, in_old, true)
            }
            Expr::Exists { var, domain, body } => {
                self.quantifier_to_rust(var, domain, body, params, fields, in_old, false)
            }
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_rust(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("{}.abs()", arg_strs[0]),
                    "min" => format!("{}.min({})", arg_strs[0], arg_strs[1]),
                    "max" => format!("{}.max({})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "todo!()".to_string(),
        }
    }

    fn stmt_to_rust(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        field_types: &HashMap<String, Type>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => {
                if let Expr::Ident(name) = &assign.value.node
                    && *name == assign.target.node
                {
                    return String::new();
                }
                format!(
                    "self.{} = {}",
                    assign.target.node,
                    self.expr_to_rust(&assign.value.node, params, fields, false)
                )
            }
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "self.{} {} {}",
                    target.node,
                    op_str,
                    self.expr_to_rust(&value.node, params, fields, false)
                )
            }
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let cond = self.clean_condition(&self.expr_to_rust(
                    &condition.node,
                    params,
                    fields,
                    false,
                ));
                let mut out = format!("if {} {{\n", cond);
                for s in then_body {
                    let stmt_code = self.stmt_to_rust(&s.node, params, fields, field_types);
                    if !stmt_code.is_empty() {
                        out.push_str(&format!("            {};\n", stmt_code));
                    }
                }
                out.push_str("        }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        let stmt_code = self.stmt_to_rust(&s.node, params, fields, field_types);
                        if !stmt_code.is_empty() {
                            out.push_str(&format!("            {};\n", stmt_code));
                        }
                    }
                    out.push_str("        }");
                }
                out
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => {
                let idx_s = self.expr_to_rust(&index.node, params, fields, false);
                let val_s = self.expr_to_rust(&value.node, params, fields, false);
                if matches!(field_types.get(&target.node), Some(Type::Map { .. })) {
                    format!("self.{}.insert({}, {})", target.node, idx_s, val_s)
                } else {
                    format!("self.{}[({}) as usize] = {}", target.node, idx_s, val_s)
                }
            }
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let idx_s = self.expr_to_rust(&index.node, params, fields, false);
                let val_s = self.expr_to_rust(&value.node, params, fields, false);
                let op_str = match op {
                    CompoundOp::Add => "+",
                    CompoundOp::Sub => "-",
                    CompoundOp::Mul => "*",
                    CompoundOp::Div => "/",
                };
                if matches!(field_types.get(&target.node), Some(Type::Map { .. })) {
                    format!(
                        "{{ let __e = self.{}.entry({}).or_insert(0); *__e = *__e {} {}; }}",
                        target.node, idx_s, op_str, val_s
                    )
                } else {
                    format!(
                        "self.{}[({}) as usize] {}= {}",
                        target.node, idx_s, op_str, val_s
                    )
                }
            }
            Statement::Assert { condition } => {
                format!(
                    "assert!({})",
                    self.expr_to_rust(&condition.node, params, fields, false)
                )
            }
            Statement::Let { name, ty, value } => {
                if let Some(explicit_ty) = ty {
                    format!(
                        "let {}: {} = {}",
                        name.node,
                        self.type_to_rust(&explicit_ty.node),
                        self.expr_to_rust(&value.node, params, fields, false)
                    )
                } else {
                    format!(
                        "let {} = {}",
                        name.node,
                        self.expr_to_rust(&value.node, params, fields, false)
                    )
                }
            }
            Statement::Match { expr, arms } => {
                let mut out = format!(
                    "match {} {{\n",
                    self.expr_to_rust(&expr.node, params, fields, false)
                );
                for arm in arms {
                    out.push_str(&format!(
                        "            {} => {{\n",
                        self.match_pattern_to_rust(&arm.pattern.node)
                    ));
                    for s in &arm.body {
                        let stmt_code = self.stmt_to_rust(&s.node, params, fields, field_types);
                        if !stmt_code.is_empty() {
                            out.push_str(&format!("                {};\n", stmt_code));
                        }
                    }
                    out.push_str("            }\n");
                }
                out.push('}');
                out
            }
        }
    }

    fn match_pattern_to_rust(&self, pattern: &MatchPattern) -> String {
        match pattern {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{}::{}", enum_name, variant)
            }
            MatchPattern::IntLit(v) => format!("{}", v),
            MatchPattern::BoolLit(v) => format!("{}", v),
            MatchPattern::StringLit(v) => format!("\"{}\"", v),
            MatchPattern::Wildcard => "_".to_string(),
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn quantifier_to_rust(
        &self,
        var: &crate::ast::span::Spanned<String>,
        domain: &crate::ast::span::Spanned<Expr>,
        body: &crate::ast::span::Spanned<Expr>,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
        is_forall: bool,
    ) -> String {
        if let Expr::Range { start, end } = &domain.node {
            let start_s = self.expr_to_rust(&start.node, params, fields, in_old);
            let end_s = self.expr_to_rust(&end.node, params, fields, in_old);
            let mut local_params = params.clone();
            local_params.insert(var.node.clone());
            let body_s = self.expr_to_rust(&body.node, &local_params, fields, in_old);

            if is_forall {
                format!(
                    "({{ let mut __verun_ok = true; for {} in ({})..({}) {{ if !({}) {{ __verun_ok = false; break; }} }} __verun_ok }})",
                    var.node, start_s, end_s, body_s
                )
            } else {
                format!(
                    "({{ let mut __verun_ok = false; for {} in ({})..({}) {{ if ({}) {{ __verun_ok = true; break; }} }} __verun_ok }})",
                    var.node, start_s, end_s, body_s
                )
            }
        } else if is_forall {
            "true".to_string()
        } else {
            "false".to_string()
        }
    }

    fn default_for_type(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "0i64".to_string(),
            Type::Real => "0.0f64".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "String::new()".to_string(),
            Type::Array { element, size } => {
                let elem_default = match element.as_ref() {
                    Type::Int => "0i64",
                    Type::Real => "0.0f64",
                    Type::Bool => "false",
                    _ => "Default::default()",
                };
                format!("[{}; {}]", elem_default, size)
            }
            Type::Map { .. } => "std::collections::HashMap::new()".to_string(),
            Type::Named(_) | Type::Enum(_) => "Default::default()".to_string(),
        }
    }

    fn clean_condition(&self, expr: &str) -> String {
        if expr.starts_with('(') && expr.ends_with(')') && expr.len() >= 2 {
            expr[1..expr.len() - 1].to_string()
        } else {
            expr.to_string()
        }
    }
}
