use std::collections::HashSet;

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct SolidityTarget;

impl CodeTarget for SolidityTarget {
    fn name(&self) -> &str {
        "solidity"
    }

    fn file_extension(&self) -> &str {
        "sol"
    }

    fn generate(&self, program: &Program) -> String {
        let mut output = String::new();
        output.push_str("// SPDX-License-Identifier: MIT\n");
        output.push_str("// Generated by Verun — do not edit manually\n");
        output.push_str("pragma solidity ^0.8.20;\n\n");

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => output.push_str(&self.gen_const(c)),
                Item::EnumDef(e) => output.push_str(&self.gen_enum(e)),
                Item::State(s) => output.push_str(&self.gen_contract(s, program)),
                _ => {}
            }
        }

        output
    }
}

impl SolidityTarget {
    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "{} constant {} = {};\n\n",
            self.type_to_sol(&c.ty.node),
            c.name.node,
            self.expr_to_sol(&c.value.node, &HashSet::new(), &HashSet::new(), false)
        )
    }

    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = format!("enum {} {{\n", e.name.node);
        for (i, variant) in e.variants.iter().enumerate() {
            out.push_str(&format!("    {}", variant.node));
            if i < e.variants.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_contract(&self, state: &StateDef, program: &Program) -> String {
        let mut out = format!("contract {} {{\n", state.name.node);

        for c in &state.constants {
            out.push_str(&format!(
                "    {} constant {} = {};\n",
                self.type_to_sol(&c.ty.node),
                c.name.node,
                self.expr_to_sol(&c.value.node, &HashSet::new(), &HashSet::new(), false)
            ));
        }
        if !state.constants.is_empty() {
            out.push('\n');
        }

        // Events from emits
        let mut events: HashSet<String> = HashSet::new();
        for t in &state.transitions {
            for emit in &t.emits {
                if events.insert(emit.node.event_name.node.clone()) {
                    let params: Vec<String> = emit
                        .node
                        .args
                        .iter()
                        .enumerate()
                        .map(|(i, _)| format!("uint256 arg{}", i))
                        .collect();
                    out.push_str(&format!(
                        "    event {}({});\n",
                        emit.node.event_name.node,
                        params.join(", ")
                    ));
                }
            }
        }
        if !events.is_empty() {
            out.push('\n');
        }

        // Enum state vars inline
        for item in &program.items {
            if let Item::EnumDef(_) = &item.node {
                // Enums already declared globally
            }
        }

        // State variables
        for field in &state.fields {
            out.push_str(&format!(
                "    {} public {};\n",
                self.type_to_sol(&field.ty.node),
                field.name.node
            ));
        }
        out.push('\n');

        // Constructor
        if let Some(init) = &state.init {
            out.push_str("    constructor() {\n");
            for assign in &init.assignments {
                out.push_str(&format!(
                    "        {} = {};\n",
                    assign.target.node,
                    self.expr_to_sol(&assign.value.node, &HashSet::new(), &HashSet::new(), false)
                ));
            }
            out.push_str("    }\n\n");
        }

        // Invariant modifier
        if !state.invariants.is_empty() {
            out.push_str("    modifier checkInvariants() {\n");
            out.push_str("        _;\n");
            for inv in &state.invariants {
                let inv_name = inv
                    .name
                    .as_ref()
                    .map(|n| n.node.as_str())
                    .unwrap_or("invariant");
                out.push_str(&format!(
                    "        require({}, \"invariant '{}' violated\");\n",
                    self.expr_to_sol(&inv.condition.node, &HashSet::new(), &HashSet::new(), false),
                    inv_name
                ));
            }
            out.push_str("    }\n\n");
        }

        // Transitions as functions
        for transition in &state.transitions {
            out.push_str(&self.gen_function(transition, state));
        }

        out.push_str("}\n");
        out
    }

    fn gen_function(&self, t: &Transition, state: &StateDef) -> String {
        let mut out = String::new();
        let param_names: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let field_names: HashSet<String> =
            state.fields.iter().map(|f| f.name.node.clone()).collect();

        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| {
                let ty = self.type_to_sol(&p.ty.node);
                let loc = self.needs_location(&p.ty.node);
                if loc.is_empty() {
                    format!("{} {}", ty, p.name.node)
                } else {
                    format!("{} {} {}", ty, loc, p.name.node)
                }
            })
            .collect();

        let modifier = if state.invariants.is_empty() {
            String::new()
        } else {
            " checkInvariants".to_string()
        };

        out.push_str(&format!(
            "    function {}({}) external{} {{\n",
            t.name.node,
            params.join(", "),
            modifier
        ));

        // Preconditions
        for pre in &t.preconditions {
            out.push_str(&format!(
                "        require({}, \"precondition failed\");\n",
                self.expr_to_sol(&pre.node, &param_names, &field_names, false)
            ));
        }

        // Save old values for postconditions
        if !t.postconditions.is_empty() {
            for field in &state.fields {
                let is_value_type = matches!(
                    field.ty.node,
                    Type::Int | Type::Real | Type::Bool | Type::Enum(_) | Type::Named(_)
                );
                if is_value_type {
                    out.push_str(&format!(
                        "        {} _old_{} = {};\n",
                        self.type_to_sol(&field.ty.node),
                        field.name.node,
                        field.name.node
                    ));
                } else {
                    out.push_str(&format!(
                        "        {} memory _old_{} = {};\n",
                        self.type_to_sol(&field.ty.node),
                        field.name.node,
                        field.name.node
                    ));
                }
            }
        }

        // Body
        for stmt in &t.body {
            out.push_str(&format!(
                "        {}\n",
                self.stmt_to_sol(&stmt.node, &param_names, &field_names)
            ));
        }

        // Postconditions
        for post in &t.postconditions {
            out.push_str(&format!(
                "        require({}, \"postcondition violated\");\n",
                self.expr_to_sol(&post.node, &param_names, &field_names, false)
            ));
        }

        // Emits
        for emit in &t.emits {
            let args: Vec<String> = emit
                .node
                .args
                .iter()
                .map(|a| self.expr_to_sol(&a.node, &param_names, &field_names, false))
                .collect();
            out.push_str(&format!(
                "        emit {}({});\n",
                emit.node.event_name.node,
                args.join(", ")
            ));
        }

        out.push_str("    }\n\n");
        out
    }

    fn type_to_sol(&self, ty: &Type) -> String {
        match ty {
            Type::Int => "int256".to_string(),
            Type::Real => "int256".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "string".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, size } => {
                format!("{}[{}]", self.type_to_sol(element), size)
            }
            Type::Map { key, value } => {
                format!(
                    "mapping({} => {})",
                    self.type_to_sol(key),
                    self.type_to_sol(value)
                )
            }
        }
    }

    fn needs_location(&self, ty: &Type) -> &str {
        match ty {
            Type::String | Type::Array { .. } => "calldata",
            _ => "",
        }
    }

    #[allow(clippy::only_used_in_recursion)]
    fn expr_to_sol(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => format!("{}", v),
            Expr::RealLit(v) => format!("{}", v),
            Expr::BoolLit(v) => format!("{}", v),
            Expr::StringLit(v) => format!("\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_sol(&inner.node, params, fields, true),
            Expr::EnumVariant { enum_name, variant } => {
                format!("{}.{}", enum_name, variant)
            }
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_sol(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("-({})", inner),
                    UnaryOp::Not => format!("!({})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_sol(&left.node, params, fields, in_old);
                let r = self.expr_to_sol(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("(!{} || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_sol(&object.node, params, fields, in_old),
                    field.node
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[{}]",
                    self.expr_to_sol(&object.node, params, fields, in_old),
                    self.expr_to_sol(&index.node, params, fields, in_old)
                )
            }
            Expr::MapAccess { map, key } => {
                format!(
                    "{}[{}]",
                    self.expr_to_sol(&map.node, params, fields, in_old),
                    self.expr_to_sol(&key.node, params, fields, in_old)
                )
            }
            Expr::Forall { .. } => "true".to_string(),
            Expr::Exists { .. } => "false".to_string(),
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_sol(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("({0} >= 0 ? {0} : -{0})", arg_strs[0]),
                    "min" => format!("({0} <= {1} ? {0} : {1})", arg_strs[0], arg_strs[1]),
                    "max" => format!("({0} >= {1} ? {0} : {1})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "true".to_string(),
        }
    }

    fn stmt_to_sol(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => {
                if let Expr::Ident(name) = &assign.value.node
                    && *name == assign.target.node
                {
                    return String::new();
                }
                format!(
                    "{} = {};",
                    assign.target.node,
                    self.expr_to_sol(&assign.value.node, params, fields, false)
                )
            }
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "{} {} {};",
                    target.node,
                    op_str,
                    self.expr_to_sol(&value.node, params, fields, false)
                )
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => {
                format!(
                    "{}[{}] = {};",
                    target.node,
                    self.expr_to_sol(&index.node, params, fields, false),
                    self.expr_to_sol(&value.node, params, fields, false)
                )
            }
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "{}[{}] {} {};",
                    target.node,
                    self.expr_to_sol(&index.node, params, fields, false),
                    op_str,
                    self.expr_to_sol(&value.node, params, fields, false)
                )
            }
            Statement::Assert { condition } => {
                format!(
                    "require({}, \"assertion failed\");",
                    self.expr_to_sol(&condition.node, params, fields, false)
                )
            }
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut out = format!(
                    "if ({}) {{\n",
                    self.expr_to_sol(&condition.node, params, fields, false)
                );
                for s in then_body {
                    let stmt_code = self.stmt_to_sol(&s.node, params, fields);
                    if !stmt_code.is_empty() {
                        out.push_str(&format!("            {}\n", stmt_code));
                    }
                }
                out.push_str("        }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        let stmt_code = self.stmt_to_sol(&s.node, params, fields);
                        if !stmt_code.is_empty() {
                            out.push_str(&format!("            {}\n", stmt_code));
                        }
                    }
                    out.push_str("        }");
                }
                out
            }
            Statement::Let { name, ty, value } => {
                let sol_ty = ty
                    .as_ref()
                    .map(|t| self.type_to_sol(&t.node))
                    .unwrap_or_else(|| "int256".to_string());
                format!(
                    "{} {} = {};",
                    sol_ty,
                    name.node,
                    self.expr_to_sol(&value.node, params, fields, false)
                )
            }
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_sol(&expr.node, params, fields, false);
                let mut out = String::new();
                for (idx, arm) in arms.iter().enumerate() {
                    if matches!(&arm.pattern.node, MatchPattern::Wildcard) {
                        if idx == 0 {
                            out.push_str("{\n");
                        } else {
                            out.push_str(" else {\n");
                        }
                    } else {
                        let cond = self.match_pattern_condition_sol(&subject, &arm.pattern.node);
                        if idx == 0 {
                            out.push_str(&format!("if ({}) {{\n", cond));
                        } else {
                            out.push_str(&format!(" else if ({}) {{\n", cond));
                        }
                    }
                    for s in &arm.body {
                        let stmt_code = self.stmt_to_sol(&s.node, params, fields);
                        if !stmt_code.is_empty() {
                            out.push_str(&format!("            {}\n", stmt_code));
                        }
                    }
                    out.push_str("        }");
                }
                out
            }
        }
    }

    fn match_pattern_condition_sol(&self, subject: &str, pattern: &MatchPattern) -> String {
        match pattern {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{} == {}.{}", subject, enum_name, variant)
            }
            MatchPattern::IntLit(v) => format!("{} == {}", subject, v),
            MatchPattern::BoolLit(v) => format!("{} == {}", subject, v),
            MatchPattern::StringLit(v) => {
                format!(
                    "keccak256(bytes({})) == keccak256(bytes(\"{}\"))",
                    subject, v
                )
            }
            MatchPattern::Wildcard => "true".to_string(),
        }
    }
}
