use std::collections::{HashMap, HashSet};

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct TypeScriptTarget;

impl CodeTarget for TypeScriptTarget {
    fn name(&self) -> &str {
        "typescript"
    }

    fn file_extension(&self) -> &str {
        "ts"
    }

    fn generate(&self, program: &Program) -> String {
        let mut output = String::new();
        output.push_str("// Generated by Verun — do not edit manually\n\n");

        for item in &program.items {
            match &item.node {
                Item::ConstDef(c) => output.push_str(&self.gen_const(c)),
                Item::EnumDef(e) => output.push_str(&self.gen_enum(e)),
                Item::TypeDef(t) => output.push_str(&self.gen_type_def(t)),
                Item::State(s) => output.push_str(&self.gen_state(s)),
                _ => {}
            }
        }

        output
    }
}

impl TypeScriptTarget {
    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "export const {}: {} = {};\n\n",
            c.name.node,
            self.type_to_ts(&c.ty.node),
            self.expr_to_ts(
                &c.value.node,
                &HashSet::new(),
                &HashSet::new(),
                &HashMap::new(),
                false,
            )
        )
    }

    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = format!("export enum {} {{\n", e.name.node);
        for variant in &e.variants {
            out.push_str(&format!("  {} = \"{}\",\n", variant.node, variant.node));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_type_def(&self, t: &crate::ast::types::TypeDef) -> String {
        if let Some(alias_ty) = &t.alias {
            return format!(
                "export type {} = {};\n\n",
                t.name.node,
                self.type_to_ts(&alias_ty.node)
            );
        }
        let mut out = format!("export interface {} {{\n", t.name.node);
        for field in &t.fields {
            out.push_str(&format!(
                "  {}: {};\n",
                field.name.node,
                self.type_to_ts(&field.ty.node)
            ));
        }
        out.push_str("}\n\n");
        out
    }

    fn gen_state(&self, state: &StateDef) -> String {
        let mut out = String::new();
        let field_types: HashMap<String, Type> = state
            .fields
            .iter()
            .map(|f| (f.name.node.clone(), f.ty.node.clone()))
            .collect();

        for c in &state.constants {
            out.push_str(&self.gen_const(c));
        }

        out.push_str(&format!("export class {} {{\n", state.name.node));

        for field in &state.fields {
            out.push_str(&format!(
                "  public {}: {};\n",
                field.name.node,
                self.type_to_ts(&field.ty.node)
            ));
        }
        out.push('\n');

        out.push_str("  constructor() {\n");
        if let Some(init) = &state.init {
            let assigned: HashSet<&str> =
                init.assignments.iter().map(|a| a.target.node.as_str()).collect();
            for assign in &init.assignments {
                out.push_str(&format!(
                    "    this.{} = {};\n",
                    assign.target.node,
                    self.expr_to_ts(
                        &assign.value.node,
                        &HashSet::new(),
                        &HashSet::new(),
                        &HashMap::new(),
                        false,
                    )
                ));
            }
            for field in &state.fields {
                if !assigned.contains(field.name.node.as_str())
                    && let Some(default) = self.default_for_ts_type(&field.ty.node)
                {
                    out.push_str(&format!("    this.{} = {};\n", field.name.node, default));
                }
            }
        } else {
            for field in &state.fields {
                if let Some(default) = self.default_for_ts_type(&field.ty.node) {
                    out.push_str(&format!("    this.{} = {};\n", field.name.node, default));
                }
            }
        }
        out.push_str("  }\n\n");

        for transition in &state.transitions {
            out.push_str(&self.gen_transition(transition, state, &field_types));
        }

        out.push_str("}\n\n");
        out
    }

    fn gen_transition(
        &self,
        t: &Transition,
        state: &StateDef,
        field_types: &HashMap<String, Type>,
    ) -> String {
        let mut out = String::new();

        let param_names: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let field_names: HashSet<String> =
            state.fields.iter().map(|f| f.name.node.clone()).collect();

        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name.node, self.type_to_ts(&p.ty.node)))
            .collect();

        out.push_str(&format!(
            "  public {}({}): void {{\n",
            t.name.node,
            params.join(", ")
        ));

        for pre in &t.preconditions {
            out.push_str(&format!(
                "    if (!({})) {{ throw new Error(\"precondition failed\"); }}\n",
                self.expr_to_ts(&pre.node, &param_names, &field_names, field_types, false)
            ));
        }

        if !t.postconditions.is_empty() {
            for field in &state.fields {
                out.push_str(&format!(
                    "    const _old_{} = this.{};\n",
                    field.name.node, field.name.node
                ));
            }
        }

        for stmt in &t.body {
            let stmt_code = self.stmt_to_ts(&stmt.node, &param_names, &field_names, field_types);
            if !stmt_code.is_empty() {
                if self.is_block_statement(&stmt.node) {
                    out.push_str(&format!("    {}\n", stmt_code));
                } else {
                    out.push_str(&format!("    {};\n", stmt_code));
                }
            }
        }

        for inv in &state.invariants {
            let inv_name = inv
                .name
                .as_ref()
                .map(|n| n.node.as_str())
                .unwrap_or("invariant");
            out.push_str(&format!(
                "    if (!({})) {{ throw new Error(\"invariant '{}' violated after '{}'\"); }}\n",
                self.expr_to_ts(&inv.condition.node, &param_names, &field_names, field_types, false),
                inv_name,
                t.name.node
            ));
        }

        for post in &t.postconditions {
            out.push_str(&format!(
                "    if (!({})) {{ throw new Error(\"postcondition violated in '{}'\"); }}\n",
                self.expr_to_ts(&post.node, &param_names, &field_names, field_types, false),
                t.name.node
            ));
        }

        out.push_str("  }\n\n");
        out
    }

    fn type_to_ts(&self, ty: &Type) -> String {
        match ty {
            Type::Int | Type::Real => "number".to_string(),
            Type::Bool => "boolean".to_string(),
            Type::String => "string".to_string(),
            Type::Named(name) => name.clone(),
            Type::Enum(name) => name.clone(),
            Type::Array { element, .. } => format!("{}[]", self.type_to_ts(element)),
            Type::Map { key, value } => {
                format!("Map<{}, {}>", self.type_to_ts(key), self.type_to_ts(value))
            }
        }
    }

    fn expr_to_ts(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        field_types: &HashMap<String, Type>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => format!("{}", v),
            Expr::RealLit(v) => format!("{}", v),
            Expr::BoolLit(v) => format!("{}", v),
            Expr::StringLit(v) => format!("\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    if matches!(field_types.get(name), Some(Type::Enum(_))) {
                        format!("(this.{} as {})", name, self.type_to_ts(&field_types[name]))
                    } else {
                        format!("this.{}", name)
                    }
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_ts(&inner.node, params, fields, field_types, true),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_ts(&operand.node, params, fields, field_types, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("(!{})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_ts(&left.node, params, fields, field_types, in_old);
                let r = self.expr_to_ts(&right.node, params, fields, field_types, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "===",
                    BinaryOp::Neq => "!==",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "&&",
                    BinaryOp::Or => "||",
                    BinaryOp::Implies => return format!("(!{} || {})", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::EnumVariant { enum_name, variant } => format!("{}.{}", enum_name, variant),
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_ts(&object.node, params, fields, field_types, in_old),
                    field.node
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[{}]",
                    self.expr_to_ts(&object.node, params, fields, field_types, in_old),
                    self.expr_to_ts(&index.node, params, fields, field_types, in_old)
                )
            }
            Expr::MapAccess { map, key } => {
                format!(
                    "({}.get({}) ?? 0)",
                    self.expr_to_ts(&map.node, params, fields, field_types, in_old),
                    self.expr_to_ts(&key.node, params, fields, field_types, in_old)
                )
            }
            Expr::Forall { var, domain, body } => {
                self.quantifier_to_ts(var, domain, body, params, fields, field_types, in_old, true)
            }
            Expr::Exists { var, domain, body } => {
                self.quantifier_to_ts(var, domain, body, params, fields, field_types, in_old, false)
            }
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_ts(&a.node, params, fields, field_types, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("Math.abs({})", arg_strs[0]),
                    "min" => format!("Math.min({}, {})", arg_strs[0], arg_strs[1]),
                    "max" => format!("Math.max({}, {})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "undefined /* unsupported */".to_string(),
        }
    }

    fn stmt_to_ts(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        field_types: &HashMap<String, Type>,
    ) -> String {
        match stmt {
            Statement::Assign(assign) => {
                if let Expr::Ident(name) = &assign.value.node
                    && *name == assign.target.node
                {
                    return String::new();
                }
                format!(
                    "this.{} = {}",
                    assign.target.node,
                    self.expr_to_ts(&assign.value.node, params, fields, field_types, false)
                )
            }
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                format!(
                    "this.{} {} {}",
                    target.node,
                    op_str,
                    self.expr_to_ts(&value.node, params, fields, field_types, false)
                )
            }
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut out = format!(
                    "if ({}) {{\n",
                    self.expr_to_ts(&condition.node, params, fields, field_types, false)
                );
                for s in then_body {
                    let stmt_code = self.stmt_to_ts(&s.node, params, fields, field_types);
                    if !stmt_code.is_empty() {
                        if self.is_block_statement(&s.node) {
                            out.push_str(&format!("      {}\n", stmt_code));
                        } else {
                            out.push_str(&format!("      {};\n", stmt_code));
                        }
                    }
                }
                out.push_str("    }");
                if let Some(else_stmts) = else_body {
                    out.push_str(" else {\n");
                    for s in else_stmts {
                        let stmt_code = self.stmt_to_ts(&s.node, params, fields, field_types);
                        if !stmt_code.is_empty() {
                            if self.is_block_statement(&s.node) {
                                out.push_str(&format!("      {}\n", stmt_code));
                            } else {
                                out.push_str(&format!("      {};\n", stmt_code));
                            }
                        }
                    }
                    out.push_str("    }");
                }
                out
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => {
                let index_s = self.expr_to_ts(&index.node, params, fields, field_types, false);
                let value_s = self.expr_to_ts(&value.node, params, fields, field_types, false);
                if matches!(field_types.get(&target.node), Some(Type::Map { .. })) {
                    format!("this.{}.set({}, {})", target.node, index_s, value_s)
                } else {
                    format!("this.{}[{}] = {}", target.node, index_s, value_s)
                }
            }
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let op_str = match op {
                    CompoundOp::Add => "+",
                    CompoundOp::Sub => "-",
                    CompoundOp::Mul => "*",
                    CompoundOp::Div => "/",
                };
                let index_s = self.expr_to_ts(&index.node, params, fields, field_types, false);
                let value_s = self.expr_to_ts(&value.node, params, fields, field_types, false);
                if matches!(field_types.get(&target.node), Some(Type::Map { .. })) {
                    format!(
                        "this.{}.set({}, (this.{}.get({}) ?? 0) {} {})",
                        target.node, index_s, target.node, index_s, op_str, value_s
                    )
                } else {
                    format!("this.{}[{}] {}= {}", target.node, index_s, op_str, value_s)
                }
            }
            Statement::Assert { condition } => {
                format!(
                    "if (!{}) {{ throw new Error(\"assertion failed\") }}",
                    self.expr_to_ts(&condition.node, params, fields, field_types, false)
                )
            }
            Statement::Let { name, value, .. } => {
                format!(
                    "const {} = {}",
                    name.node,
                    self.expr_to_ts(&value.node, params, fields, field_types, false)
                )
            }
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_ts(&expr.node, params, fields, field_types, false);
                let mut out = String::new();
                for (idx, arm) in arms.iter().enumerate() {
                    let prefix = if idx == 0 { "if" } else { "else if" };
                    let cond = self.match_pattern_condition_ts(&subject, &arm.pattern.node);
                    if matches!(&arm.pattern.node, MatchPattern::Wildcard) {
                        if idx == 0 {
                            out.push_str("{\n");
                        } else {
                            out.push_str(" else {\n");
                        }
                    } else {
                        out.push_str(&format!("{} ({}) {{\n", prefix, cond));
                    }
                    for s in &arm.body {
                        let stmt_code = self.stmt_to_ts(&s.node, params, fields, field_types);
                        if !stmt_code.is_empty() {
                            if self.is_block_statement(&s.node) {
                                out.push_str(&format!("      {}\n", stmt_code));
                            } else {
                                out.push_str(&format!("      {};\n", stmt_code));
                            }
                        }
                    }
                    out.push_str("    }");
                }
                out
            }
        }
    }

    fn is_block_statement(&self, stmt: &Statement) -> bool {
        matches!(stmt, Statement::If { .. } | Statement::Match { .. })
    }

    #[allow(clippy::too_many_arguments)]
    fn quantifier_to_ts(
        &self,
        var: &crate::ast::span::Spanned<String>,
        domain: &crate::ast::span::Spanned<Expr>,
        body: &crate::ast::span::Spanned<Expr>,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        field_types: &HashMap<String, Type>,
        in_old: bool,
        is_forall: bool,
    ) -> String {
        if let Expr::Range { start, end } = &domain.node {
            let start_s = self.expr_to_ts(&start.node, params, fields, field_types, in_old);
            let end_s = self.expr_to_ts(&end.node, params, fields, field_types, in_old);
            let mut local_params = params.clone();
            local_params.insert(var.node.clone());
            let body_s = self.expr_to_ts(&body.node, &local_params, fields, field_types, in_old);

            if is_forall {
                format!(
                    "(() => {{ for (let {} = ({}); {} < ({}); {}++) {{ if (!({})) return false; }} return true; }})()",
                    var.node, start_s, var.node, end_s, var.node, body_s
                )
            } else {
                format!(
                    "(() => {{ for (let {} = ({}); {} < ({}); {}++) {{ if (({})) return true; }} return false; }})()",
                    var.node, start_s, var.node, end_s, var.node, body_s
                )
            }
        } else if is_forall {
            "true".to_string()
        } else {
            "false".to_string()
        }
    }

    fn match_pattern_condition_ts(&self, subject: &str, pattern: &MatchPattern) -> String {
        match pattern {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{} === {}.{}", subject, enum_name, variant)
            }
            MatchPattern::IntLit(v) => format!("{} === {}", subject, v),
            MatchPattern::BoolLit(v) => format!("{} === {}", subject, v),
            MatchPattern::StringLit(v) => format!("{} === \"{}\"", subject, v),
            MatchPattern::Wildcard => "true".to_string(),
        }
    }

    fn default_for_ts_type(&self, ty: &Type) -> Option<String> {
        match ty {
            Type::Array { element, size } => {
                Some(format!("new Array({}).fill({})", size, self.zero_for_ts_type(element)))
            }
            Type::Map { .. } => Some("new Map()".to_string()),
            _ => None,
        }
    }

    fn zero_for_ts_type(&self, ty: &Type) -> String {
        match ty {
            Type::Int | Type::Real => "0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "\"\"".to_string(),
            _ => "undefined".to_string(),
        }
    }
}
