use std::collections::HashSet;

use crate::ast::nodes::*;
use crate::ast::types::Type;

use super::target::CodeTarget;

pub struct VyperTarget;

impl CodeTarget for VyperTarget {
    fn name(&self) -> &str {
        "vyper"
    }

    fn file_extension(&self) -> &str {
        "vy"
    }

    fn generate(&self, program: &Program) -> String {
        let mut out = String::new();
        out.push_str("# Generated by Verun\n\n");

        for item in &program.items {
            match &item.node {
                Item::EnumDef(e) => out.push_str(&self.gen_enum(e)),
                Item::ConstDef(c) => out.push_str(&self.gen_const(c)),
                _ => {}
            }
        }

        for item in &program.items {
            if let Item::State(state) = &item.node {
                out.push_str(&self.gen_contract(state));
            }
        }

        out
    }
}

impl VyperTarget {
    fn gen_enum(&self, e: &crate::ast::types::EnumDef) -> String {
        let mut out = format!("enum {}:\n", e.name.node);
        for variant in &e.variants {
            out.push_str(&format!("    {}\n", variant.node));
        }
        out.push('\n');
        out
    }

    fn gen_const(&self, c: &ConstDef) -> String {
        format!(
            "{}: constant({}) = {}\n\n",
            c.name.node,
            self.type_to_vyper(&c.ty.node),
            self.expr_to_vyper(&c.value.node, &HashSet::new(), &HashSet::new(), false)
        )
    }

    fn gen_contract(&self, state: &StateDef) -> String {
        let mut out = String::new();

        for c in &state.constants {
            out.push_str(&self.gen_const(c));
        }

        for field in &state.fields {
            out.push_str(&format!(
                "{}: public({})\n",
                field.name.node,
                self.type_to_vyper(&field.ty.node)
            ));
        }
        out.push('\n');

        out.push_str("@deploy\n");
        out.push_str("def __init__():\n");
        if let Some(init) = &state.init {
            for assign in &init.assignments {
                out.push_str(&format!(
                    "    self.{} = {}\n",
                    assign.target.node,
                    self.expr_to_vyper(&assign.value.node, &HashSet::new(), &HashSet::new(), false)
                ));
            }
        } else {
            out.push_str("    pass\n");
        }
        out.push('\n');

        for t in &state.transitions {
            out.push_str(&self.gen_transition(state, t));
        }

        out
    }

    fn gen_transition(&self, state: &StateDef, t: &Transition) -> String {
        let params: Vec<String> = t
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name.node, self.type_to_vyper(&p.ty.node)))
            .collect();
        let params_set: HashSet<String> = t.params.iter().map(|p| p.name.node.clone()).collect();
        let fields_set: HashSet<String> =
            state.fields.iter().map(|f| f.name.node.clone()).collect();

        let mut out = String::new();
        out.push_str("@external\n");
        out.push_str(&format!("def {}({}):\n", t.name.node, params.join(", ")));

        let mut body_lines: Vec<String> = Vec::new();

        for pre in &t.preconditions {
            body_lines.push(format!(
                "assert {}, \"precondition failed\"",
                self.expr_to_vyper(&pre.node, &params_set, &fields_set, false)
            ));
        }

        if !t.postconditions.is_empty() {
            for field in &state.fields {
                body_lines.push(format!(
                    "_old_{}: {} = self.{}",
                    field.name.node,
                    self.type_to_vyper(&field.ty.node),
                    field.name.node
                ));
            }
        }

        for stmt in &t.body {
            body_lines.extend(self.stmt_to_vyper_lines(&stmt.node, &params_set, &fields_set, 0));
        }

        for inv in &state.invariants {
            let inv_name = inv
                .name
                .as_ref()
                .map(|n| n.node.as_str())
                .unwrap_or("invariant");
            body_lines.push(format!(
                "assert {}, \"invariant '{}' violated\"",
                self.expr_to_vyper(&inv.condition.node, &params_set, &fields_set, false),
                inv_name
            ));
        }

        for post in &t.postconditions {
            body_lines.push(format!(
                "assert {}, \"postcondition violated\"",
                self.expr_to_vyper(&post.node, &params_set, &fields_set, false)
            ));
        }

        if body_lines.is_empty() {
            out.push_str("    pass\n\n");
        } else {
            for line in body_lines {
                out.push_str("    ");
                out.push_str(&line);
                out.push('\n');
            }
            out.push('\n');
        }

        out
    }

    fn type_to_vyper(&self, ty: &Type) -> String {
        match ty {
            Type::Int | Type::Real => "int256".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String[256]".to_string(),
            Type::Named(name) | Type::Enum(name) => name.clone(),
            Type::Array { element, size } => format!("{}[{}]", self.type_to_vyper(element), size),
            Type::Map { key, value } => format!(
                "HashMap[{}, {}]",
                self.type_to_vyper(key),
                self.type_to_vyper(value)
            ),
        }
    }

    fn expr_to_vyper(
        &self,
        expr: &Expr,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        in_old: bool,
    ) -> String {
        match expr {
            Expr::IntLit(v) => v.to_string(),
            Expr::RealLit(v) => format!("{}", *v as i64),
            Expr::BoolLit(v) => v.to_string(),
            Expr::StringLit(v) => format!("\"{}\"", v),
            Expr::Ident(name) => {
                if params.contains(name) {
                    name.clone()
                } else if in_old {
                    format!("_old_{}", name)
                } else if fields.contains(name) {
                    format!("self.{}", name)
                } else {
                    name.clone()
                }
            }
            Expr::Old(inner) => self.expr_to_vyper(&inner.node, params, fields, true),
            Expr::EnumVariant { enum_name, variant } => format!("{}.{}", enum_name, variant),
            Expr::UnaryOp { op, operand } => {
                let inner = self.expr_to_vyper(&operand.node, params, fields, in_old);
                match op {
                    UnaryOp::Neg => format!("(-{})", inner),
                    UnaryOp::Not => format!("not ({})", inner),
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.expr_to_vyper(&left.node, params, fields, in_old);
                let r = self.expr_to_vyper(&right.node, params, fields, in_old);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                    BinaryOp::Mod => "%",
                    BinaryOp::Eq => "==",
                    BinaryOp::Neq => "!=",
                    BinaryOp::Lt => "<",
                    BinaryOp::Gt => ">",
                    BinaryOp::Lte => "<=",
                    BinaryOp::Gte => ">=",
                    BinaryOp::And => "and",
                    BinaryOp::Or => "or",
                    BinaryOp::Implies => return format!("((not ({})) or ({}))", l, r),
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FieldAccess { object, field } => {
                format!(
                    "{}.{}",
                    self.expr_to_vyper(&object.node, params, fields, in_old),
                    field.node
                )
            }
            Expr::IndexAccess { object, index } => {
                format!(
                    "{}[{}]",
                    self.expr_to_vyper(&object.node, params, fields, in_old),
                    self.expr_to_vyper(&index.node, params, fields, in_old)
                )
            }
            Expr::MapAccess { map, key } => {
                format!(
                    "{}[{}]",
                    self.expr_to_vyper(&map.node, params, fields, in_old),
                    self.expr_to_vyper(&key.node, params, fields, in_old)
                )
            }
            Expr::Forall { .. } => "True".to_string(),
            Expr::Exists { .. } => "False".to_string(),
            Expr::FnCall { name, args } => {
                let arg_strs: Vec<String> = args
                    .iter()
                    .map(|a| self.expr_to_vyper(&a.node, params, fields, in_old))
                    .collect();
                match name.node.as_str() {
                    "abs" => format!("abs({})", arg_strs[0]),
                    "min" => format!("min({}, {})", arg_strs[0], arg_strs[1]),
                    "max" => format!("max({}, {})", arg_strs[0], arg_strs[1]),
                    _ => format!("{}({})", name.node, arg_strs.join(", ")),
                }
            }
            _ => "0".to_string()
        }
    }

    fn stmt_to_vyper_lines(
        &self,
        stmt: &Statement,
        params: &HashSet<String>,
        fields: &HashSet<String>,
        indent: usize,
    ) -> Vec<String> {
        let pad = "    ".repeat(indent);
        match stmt {
            Statement::Assign(assign) => vec![format!(
                "{}self.{} = {}",
                pad,
                assign.target.node,
                self.expr_to_vyper(&assign.value.node, params, fields, false)
            )],
            Statement::CompoundAssign { target, op, value } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                vec![format!(
                    "{}self.{} {} {}",
                    pad,
                    target.node,
                    op_str,
                    self.expr_to_vyper(&value.node, params, fields, false)
                )]
            }
            Statement::IndexedAssign {
                target,
                index,
                value,
            } => vec![format!(
                "{}self.{}[{}] = {}",
                pad,
                target.node,
                self.expr_to_vyper(&index.node, params, fields, false),
                self.expr_to_vyper(&value.node, params, fields, false)
            )],
            Statement::IndexedCompoundAssign {
                target,
                index,
                op,
                value,
            } => {
                let op_str = match op {
                    CompoundOp::Add => "+=",
                    CompoundOp::Sub => "-=",
                    CompoundOp::Mul => "*=",
                    CompoundOp::Div => "/=",
                };
                vec![format!(
                    "{}self.{}[{}] {} {}",
                    pad,
                    target.node,
                    self.expr_to_vyper(&index.node, params, fields, false),
                    op_str,
                    self.expr_to_vyper(&value.node, params, fields, false)
                )]
            }
            Statement::Assert { condition } => vec![format!(
                "{}assert {}, \"assertion failed\"",
                pad,
                self.expr_to_vyper(&condition.node, params, fields, false)
            )],
            Statement::Let { name, value, .. } => vec![format!(
                "{}{}: int256 = {}",
                pad,
                name.node,
                self.expr_to_vyper(&value.node, params, fields, false)
            )],
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                let mut lines = vec![format!(
                    "{}if {}:",
                    pad,
                    self.expr_to_vyper(&condition.node, params, fields, false)
                )];
                if then_body.is_empty() {
                    lines.push(format!("{}    pass", pad));
                } else {
                    for s in then_body {
                        lines.extend(self.stmt_to_vyper_lines(&s.node, params, fields, indent + 1));
                    }
                }
                if let Some(else_stmts) = else_body {
                    lines.push(format!("{}else:", pad));
                    if else_stmts.is_empty() {
                        lines.push(format!("{}    pass", pad));
                    } else {
                        for s in else_stmts {
                            lines.extend(self.stmt_to_vyper_lines(
                                &s.node,
                                params,
                                fields,
                                indent + 1,
                            ));
                        }
                    }
                }
                lines
            }
            Statement::Match { expr, arms } => {
                let subject = self.expr_to_vyper(&expr.node, params, fields, false);
                let mut lines: Vec<String> = Vec::new();
                for (idx, arm) in arms.iter().enumerate() {
                    match &arm.pattern.node {
                        MatchPattern::Wildcard => lines.push(format!("{}else:", pad)),
                        _ => {
                            let kw = if idx == 0 { "if" } else { "elif" };
                            lines.push(format!(
                                "{}{} {} == {}:",
                                pad,
                                kw,
                                subject,
                                self.pattern_to_vyper(&arm.pattern.node)
                            ));
                        }
                    }
                    if arm.body.is_empty() {
                        lines.push(format!("{}    pass", pad));
                    } else {
                        for s in &arm.body {
                            lines.extend(self.stmt_to_vyper_lines(
                                &s.node,
                                params,
                                fields,
                                indent + 1,
                            ));
                        }
                    }
                }
                lines
            }
        }
    }

    fn pattern_to_vyper(&self, p: &MatchPattern) -> String {
        match p {
            MatchPattern::EnumVariant { enum_name, variant } => {
                format!("{}.{}", enum_name, variant)
            }
            MatchPattern::IntLit(v) => v.to_string(),
            MatchPattern::BoolLit(v) => v.to_string(),
            MatchPattern::StringLit(v) => format!("\"{}\"", v),
            MatchPattern::Wildcard => "_".to_string(),
        }
    }
}
